{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-jte/2.0.2-jitsi/ktor-server-jte-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-jte",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-jte-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-jte-jvm-2.0.2-jitsi.jar",
          "size": 12430,
          "sha512": "3345629ea55b4d88ea5302888427f404b0ea54611a2a54f97ce8eb6885792a9cf5d772df42bbd46845f5bfd1b4b9207b98de2cf3ac9a5716fbc4208cc1322399",
          "sha256": "7f576ece5de7a34615f68c72964e4b15e2c2e5a9793c2b93eb3adc1c5387b4c0",
          "sha1": "6b447565a94a3eea2a014d1ff0f09b8e224a012b",
          "md5": "ebd0da2bba216d9990e22e1557e100df"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "gg.jte",
          "module": "jte",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-jte-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-jte-jvm-2.0.2-jitsi.jar",
          "size": 12430,
          "sha512": "3345629ea55b4d88ea5302888427f404b0ea54611a2a54f97ce8eb6885792a9cf5d772df42bbd46845f5bfd1b4b9207b98de2cf3ac9a5716fbc4208cc1322399",
          "sha256": "7f576ece5de7a34615f68c72964e4b15e2c2e5a9793c2b93eb3adc1c5387b4c0",
          "sha1": "6b447565a94a3eea2a014d1ff0f09b8e224a012b",
          "md5": "ebd0da2bba216d9990e22e1557e100df"
        }
      ]
    }
  ]
}
