{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-legacy",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-legacy-4.4.8-jitsi-1.jar",
          "url": "smack-legacy-4.4.8-jitsi-1.jar",
          "size": 183187,
          "sha512": "20b8c831ea067c06bd1ed07ba963814ecb7b112bf04e0fd8cb6443af0d12363b6f86b2a4197781cac7d772a191c4ca688e16f2e0808e7eaddc1237fe3fdbc2cd",
          "sha256": "c12349820fef0a8c06690864c84f3133e961bcedc13329c6d19d20454eb78f0e",
          "sha1": "b63fde48c25cc323ecdf9b0255d8a4dc5c64e9db",
          "md5": "56d8bfa777ec6d15f3f16672c31d785c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-legacy-4.4.8-jitsi-1.jar",
          "url": "smack-legacy-4.4.8-jitsi-1.jar",
          "size": 183187,
          "sha512": "20b8c831ea067c06bd1ed07ba963814ecb7b112bf04e0fd8cb6443af0d12363b6f86b2a4197781cac7d772a191c4ca688e16f2e0808e7eaddc1237fe3fdbc2cd",
          "sha256": "c12349820fef0a8c06690864c84f3133e961bcedc13329c6d19d20454eb78f0e",
          "sha1": "b63fde48c25cc323ecdf9b0255d8a4dc5c64e9db",
          "md5": "56d8bfa777ec6d15f3f16672c31d785c"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-legacy-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-legacy-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "d224a10ba260492d420e249ae3db11ae047d369f8fd7a2d76229c7e8869d653462b9dcb8a20200509a7108615206cf3dcb7afb421e928e67e9ecedc9a02e91ee",
          "sha256": "8916274574c3f89a6d34b5201a05a06e93ba306aae600cf68111557e6eedba75",
          "sha1": "874a9b9ae58d985b7a3ac35b4d7a470896dec571",
          "md5": "91a1178f4e4599cd79d7fbfe305fe468"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-legacy-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-legacy-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-legacy-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "d224a10ba260492d420e249ae3db11ae047d369f8fd7a2d76229c7e8869d653462b9dcb8a20200509a7108615206cf3dcb7afb421e928e67e9ecedc9a02e91ee",
          "sha256": "8916274574c3f89a6d34b5201a05a06e93ba306aae600cf68111557e6eedba75",
          "sha1": "874a9b9ae58d985b7a3ac35b4d7a470896dec571",
          "md5": "91a1178f4e4599cd79d7fbfe305fe468"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-legacy-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
