{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-jingle-old",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "javax.media",
          "module": "jmf",
          "version": {
            "requires": "2.1.1e"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "size": 260552,
          "sha512": "f4592023c3189e46ffd6d554d7a2b18fe2dfac5ab585ca1c52d1af1a354ae6cad6861ceb5057e980129e974637e1dca16635bd0ea483cfb3a0e7d7c207c55999",
          "sha256": "96ee77c8ce12cb1dd6234757741608f6c1e10a4be79ff024aa4dfac49d7883f2",
          "sha1": "2442b31c102bf53aa38dc1d184c30abf14944d75",
          "md5": "2ec217c754a68bacc096133e675acaa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "javax.media",
          "module": "jmf",
          "version": {
            "requires": "2.1.1e"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "size": 260552,
          "sha512": "f4592023c3189e46ffd6d554d7a2b18fe2dfac5ab585ca1c52d1af1a354ae6cad6861ceb5057e980129e974637e1dca16635bd0ea483cfb3a0e7d7c207c55999",
          "sha256": "96ee77c8ce12cb1dd6234757741608f6c1e10a4be79ff024aa4dfac49d7883f2",
          "sha1": "2442b31c102bf53aa38dc1d184c30abf14944d75",
          "md5": "2ec217c754a68bacc096133e675acaa7"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-jingle-old",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "d224a10ba260492d420e249ae3db11ae047d369f8fd7a2d76229c7e8869d653462b9dcb8a20200509a7108615206cf3dcb7afb421e928e67e9ecedc9a02e91ee",
          "sha256": "8916274574c3f89a6d34b5201a05a06e93ba306aae600cf68111557e6eedba75",
          "sha1": "874a9b9ae58d985b7a3ac35b4d7a470896dec571",
          "md5": "91a1178f4e4599cd79d7fbfe305fe468"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-jingle-old-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-jingle-old",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "d224a10ba260492d420e249ae3db11ae047d369f8fd7a2d76229c7e8869d653462b9dcb8a20200509a7108615206cf3dcb7afb421e928e67e9ecedc9a02e91ee",
          "sha256": "8916274574c3f89a6d34b5201a05a06e93ba306aae600cf68111557e6eedba75",
          "sha1": "874a9b9ae58d985b7a3ac35b4d7a470896dec571",
          "md5": "91a1178f4e4599cd79d7fbfe305fe468"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-jingle-old-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
