{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-android",
    "version": "4.4.8-jitsi-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uuvftdk5hzaffihqimktnt4x7e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.minidns",
          "module": "minidns-android21",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-sasl-provided",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-xpp3",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-4.4.8-jitsi-2.jar",
          "url": "smack-android-4.4.8-jitsi-2.jar",
          "size": 5800,
          "sha512": "f0b08d8c7b80c366d56ecfae492442c74555df4cbad168281facc35ef127488d32b98c6d591d5fc606d9d4f7f103e9791ba7080ff5518ac3b5b296bc8371b6a0",
          "sha256": "3a2250ea18901d8d571e21b824ef540d333e22f0b818875cc71f672493d3b975",
          "sha1": "04d657aeddfcc49bba29fb58d91aa21185296801",
          "md5": "a9a14b961cb0744c7a75040f6ba5c737"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-xpp3",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-android21",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-sasl-provided",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-4.4.8-jitsi-2.jar",
          "url": "smack-android-4.4.8-jitsi-2.jar",
          "size": 5800,
          "sha512": "f0b08d8c7b80c366d56ecfae492442c74555df4cbad168281facc35ef127488d32b98c6d591d5fc606d9d4f7f103e9791ba7080ff5518ac3b5b296bc8371b6a0",
          "sha256": "3a2250ea18901d8d571e21b824ef540d333e22f0b818875cc71f672493d3b975",
          "sha1": "04d657aeddfcc49bba29fb58d91aa21185296801",
          "md5": "a9a14b961cb0744c7a75040f6ba5c737"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-4.4.8-jitsi-2-test-fixtures.jar",
          "url": "smack-android-4.4.8-jitsi-2-test-fixtures.jar",
          "size": 261,
          "sha512": "864cc751e82d4e658edb69dcb20332065aee5dbcdf8da18908c8e95c9997152b30f7a80a2dec4d39ea762c65d68701f03aa851463666af205c79cd7b76dbe422",
          "sha256": "f489a4cc5b38c8a85decf2c67dc22827921355fe6cb1646dedd9b63b662e3d87",
          "sha1": "7cc24439c9addb6db22e370d95003a15be674880",
          "md5": "ef6f712f4e716bf33f0cc51c54ed089a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-android-test-fixtures",
          "version": "4.4.8-jitsi-2"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-4.4.8-jitsi-2-test-fixtures.jar",
          "url": "smack-android-4.4.8-jitsi-2-test-fixtures.jar",
          "size": 261,
          "sha512": "864cc751e82d4e658edb69dcb20332065aee5dbcdf8da18908c8e95c9997152b30f7a80a2dec4d39ea762c65d68701f03aa851463666af205c79cd7b76dbe422",
          "sha256": "f489a4cc5b38c8a85decf2c67dc22827921355fe6cb1646dedd9b63b662e3d87",
          "sha1": "7cc24439c9addb6db22e370d95003a15be674880",
          "md5": "ef6f712f4e716bf33f0cc51c54ed089a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-android-test-fixtures",
          "version": "4.4.8-jitsi-2"
        }
      ]
    }
  ]
}
