{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-auth/2.0.2-jitsi/ktor-client-auth-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-auth",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-auth-jvm-2.0.2-jitsi.jar",
          "size": 73030,
          "sha512": "552461d6359a74247c67f01ec229c11f4c6c85e202a9ebe11ec3a705806027e9713bf9f6175cf68682db8506ea0f06fbf6c191e472c2b68c94ae5da189aea851",
          "sha256": "6d5b757d7e49dcd778ee954f3610776ca465a9afdb118affbd43a34e5b0e1d0b",
          "sha1": "2d7467b0d631096e3d6f8089c8d33ed6ae8f835b",
          "md5": "1aed23c310265a6e4fb40ca85eb655b2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-auth-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-auth-jvm-2.0.2-jitsi.jar",
          "size": 73030,
          "sha512": "552461d6359a74247c67f01ec229c11f4c6c85e202a9ebe11ec3a705806027e9713bf9f6175cf68682db8506ea0f06fbf6c191e472c2b68c94ae5da189aea851",
          "sha256": "6d5b757d7e49dcd778ee954f3610776ca465a9afdb118affbd43a34e5b0e1d0b",
          "sha1": "2d7467b0d631096e3d6f8089c8d33ed6ae8f835b",
          "md5": "1aed23c310265a6e4fb40ca85eb655b2"
        }
      ]
    }
  ]
}
