{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-java8-full",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-3.jar",
          "url": "smack-java8-full-4.4.8-jitsi-3.jar",
          "size": 2645,
          "sha512": "b9329331bc080984b1efc95756a9d69cbe81995cd94511f4eb66aa74e696861bf683e5c97f7a8b7528e501c9db1aa37ba5c0e213d5d6f6936a36dd422b7e6a7b",
          "sha256": "6be7fca1313e27c7e0a4673c11c3f3de00d8d9096ea29d151558537e44aeadbe",
          "sha1": "5c3d82b8ecef912d26d14a326fbd328c1c58363b",
          "md5": "012d3279c5b439c6b6786aed8d0bb11f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-3.jar",
          "url": "smack-java8-full-4.4.8-jitsi-3.jar",
          "size": 2645,
          "sha512": "b9329331bc080984b1efc95756a9d69cbe81995cd94511f4eb66aa74e696861bf683e5c97f7a8b7528e501c9db1aa37ba5c0e213d5d6f6936a36dd422b7e6a7b",
          "sha256": "6be7fca1313e27c7e0a4673c11c3f3de00d8d9096ea29d151558537e44aeadbe",
          "sha1": "5c3d82b8ecef912d26d14a326fbd328c1c58363b",
          "md5": "012d3279c5b439c6b6786aed8d0bb11f"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "e72e081b8e12eeab09ac8e8d6cd08e40557499c2367d43f341a59b7362071ed69e34d6d99be594d20adf88060204cdb99285ae1be7be1bee111ec3abaf5fe345",
          "sha256": "255063df4e4acc293dc399deb2358431babf76388c80b5e791cd97959a56fccc",
          "sha1": "64dc3ffbbeb2851265c47e250727930c93cbad10",
          "md5": "42e9436ac1548c889872953b449f00a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "e72e081b8e12eeab09ac8e8d6cd08e40557499c2367d43f341a59b7362071ed69e34d6d99be594d20adf88060204cdb99285ae1be7be1bee111ec3abaf5fe345",
          "sha256": "255063df4e4acc293dc399deb2358431babf76388c80b5e791cd97959a56fccc",
          "sha1": "64dc3ffbbeb2851265c47e250727930c93cbad10",
          "md5": "42e9436ac1548c889872953b449f00a9"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
