{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-okhttp/2.0.2-jitsi/ktor-client-okhttp-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-okhttp",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-okhttp-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-okhttp-jvm-2.0.2-jitsi.jar",
          "size": 61332,
          "sha512": "e33e97df1fc7cf956305311a1e60462238961dda9c86ed72006604df636fb0c33b0f2eec8818ad40450e30a9c34c491c595d0d81200e3a4e60ff7c646d155ba6",
          "sha256": "68f4b9e1e88ac52a97fcc545480f35e2ba0a90c95a146991b883cd8dd517dfd0",
          "sha1": "c3a39c816f2117813a76f8b60c2ebde4faaf7959",
          "md5": "09ce5e33fdda7c1f3d4cb77847fcc323"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-okhttp-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-okhttp-jvm-2.0.2-jitsi.jar",
          "size": 61332,
          "sha512": "e33e97df1fc7cf956305311a1e60462238961dda9c86ed72006604df636fb0c33b0f2eec8818ad40450e30a9c34c491c595d0d81200e3a4e60ff7c646d155ba6",
          "sha256": "68f4b9e1e88ac52a97fcc545480f35e2ba0a90c95a146991b883cd8dd517dfd0",
          "sha1": "c3a39c816f2117813a76f8b60c2ebde4faaf7959",
          "md5": "09ce5e33fdda7c1f3d4cb77847fcc323"
        }
      ]
    }
  ]
}
