{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-omemo",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-1.jar",
          "url": "smack-omemo-4.4.8-jitsi-1.jar",
          "size": 117850,
          "sha512": "89d09f76714eae0bedd4c3e6bbed438a655f6c1f53e612fc11dc7f928075b3acac962e26c68da4233c18faa7b38e57d49bcb159240b989cfe890c422cdf5acc9",
          "sha256": "6bfbe488bd094b23b90057fc179efb55f653b1541ed80f1103eb0f04eb2f8899",
          "sha1": "2dfb668fd4f6bc7ee5003237588a6229658c212d",
          "md5": "260301e79a6f3daa27c25b5d79b22272"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-1.jar",
          "url": "smack-omemo-4.4.8-jitsi-1.jar",
          "size": 117850,
          "sha512": "89d09f76714eae0bedd4c3e6bbed438a655f6c1f53e612fc11dc7f928075b3acac962e26c68da4233c18faa7b38e57d49bcb159240b989cfe890c422cdf5acc9",
          "sha256": "6bfbe488bd094b23b90057fc179efb55f653b1541ed80f1103eb0f04eb2f8899",
          "sha1": "2dfb668fd4f6bc7ee5003237588a6229658c212d",
          "md5": "260301e79a6f3daa27c25b5d79b22272"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-omemo-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "63b082c78b9983061130ffe335e6233ee3824fb37626df7ef738ae0acce461be6f9c94c6838d15751b2f657fcb2db98955480fee73e11ba58b284c335d671e19",
          "sha256": "a01e08c33b9edc26fb0f7a4e8a1b8b8ee79b6a1d3834eb67123e7427296ae49d",
          "sha1": "b33bb22425240fba74c4d16b8a8e9dc2c1edac88",
          "md5": "4787454568233e3b37c91f141dfd6d72"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-omemo-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-omemo-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "63b082c78b9983061130ffe335e6233ee3824fb37626df7ef738ae0acce461be6f9c94c6838d15751b2f657fcb2db98955480fee73e11ba58b284c335d671e19",
          "sha256": "a01e08c33b9edc26fb0f7a4e8a1b8b8ee79b6a1d3834eb67123e7427296ae49d",
          "sha1": "b33bb22425240fba74c4d16b8a8e9dc2c1edac88",
          "md5": "4787454568233e3b37c91f141dfd6d72"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-omemo-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
