{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-repl",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "com.lihaoyi",
          "module": "ammonite_2.12.1",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-3.jar",
          "url": "smack-repl-4.4.8-jitsi-3.jar",
          "size": 32694,
          "sha512": "08c7e9e3da597e4c116457ba68bd9eea23dab6f11da5d696a66a4b76284c2ca68c8c677c7953259baef802eae3ac5663a59dc66be9dcf3e711c00013cc2b98b3",
          "sha256": "95c86c6d38f03769ee62fe1e5b25800d4fcbec0869c64143d1db5c9d0e5ca0b9",
          "sha1": "94990ac6117a896152bf8ce928a0864f48b3e946",
          "md5": "192b77c02235fbc0c9938702c56c08c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "com.lihaoyi",
          "module": "ammonite_2.12.1",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-3.jar",
          "url": "smack-repl-4.4.8-jitsi-3.jar",
          "size": 32694,
          "sha512": "08c7e9e3da597e4c116457ba68bd9eea23dab6f11da5d696a66a4b76284c2ca68c8c677c7953259baef802eae3ac5663a59dc66be9dcf3e711c00013cc2b98b3",
          "sha256": "95c86c6d38f03769ee62fe1e5b25800d4fcbec0869c64143d1db5c9d0e5ca0b9",
          "sha1": "94990ac6117a896152bf8ce928a0864f48b3e946",
          "md5": "192b77c02235fbc0c9938702c56c08c6"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-repl",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-repl-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "074c2b2dc70c64a146ecc9ac59a5e71f95fa360912b63493e7682e3b22f660947e9087445db8ec37f6f22617a44cebb869b674228ccb3efa9f294f50f4613c2b",
          "sha256": "958a7db816c72261d8c4df0e3a09b9ecfc7bb54f55ad26f9a96e1deb119fc75f",
          "sha1": "8d48fd92f3affe829ea72eb086be59e9f10aa8f2",
          "md5": "58dcabf20c4fb7ff8361372de0bc9bf8"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-repl-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-repl",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-repl-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "074c2b2dc70c64a146ecc9ac59a5e71f95fa360912b63493e7682e3b22f660947e9087445db8ec37f6f22617a44cebb869b674228ccb3efa9f294f50f4613c2b",
          "sha256": "958a7db816c72261d8c4df0e3a09b9ecfc7bb54f55ad26f9a96e1deb119fc75f",
          "sha1": "8d48fd92f3affe829ea72eb086be59e9f10aa8f2",
          "md5": "58dcabf20c4fb7ff8361372de0bc9bf8"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-repl-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
