{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-minidns-dox",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-3.jar",
          "size": 2602,
          "sha512": "7fd200fe6fdb0ce64f1aa3ff2cd8b00ccd18ea0d808325f636fc2169176f703504dc3d3f9537446bec657d3870d9528e9dfdcf03d24a9901d1860f43003ceae0",
          "sha256": "88cad57912cd98944d70cca82875b0496899f5ed2f7da03e626301e4ad935acc",
          "sha1": "25deb4883499264ff98255b852f0a35e9c423c58",
          "md5": "9ad860e08e3527c5c97c173ac727e193"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-3.jar",
          "size": 2602,
          "sha512": "7fd200fe6fdb0ce64f1aa3ff2cd8b00ccd18ea0d808325f636fc2169176f703504dc3d3f9537446bec657d3870d9528e9dfdcf03d24a9901d1860f43003ceae0",
          "sha256": "88cad57912cd98944d70cca82875b0496899f5ed2f7da03e626301e4ad935acc",
          "sha1": "25deb4883499264ff98255b852f0a35e9c423c58",
          "md5": "9ad860e08e3527c5c97c173ac727e193"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "0aba01a214edfe39ecc72158590449166cff2802b6ecb1ab968841cd4b8fec11d770510d013aea2041b2dc30fa6c591681efd80813e6d75e3dd0a93f3eb28fb9",
          "sha256": "a46691c57384b5d570f2b4f92657b8e495c0352d023b2b3bb6f0d991973f455d",
          "sha1": "3f0e91241198bdf02635d6a5a397f47dffe3ae33",
          "md5": "1e27f05b1c38ca8463b6168e7829b15d"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-dox-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "0aba01a214edfe39ecc72158590449166cff2802b6ecb1ab968841cd4b8fec11d770510d013aea2041b2dc30fa6c591681efd80813e6d75e3dd0a93f3eb28fb9",
          "sha256": "a46691c57384b5d570f2b4f92657b8e495c0352d023b2b3bb6f0d991973f455d",
          "sha1": "3f0e91241198bdf02635d6a5a397f47dffe3ae33",
          "md5": "1e27f05b1c38ca8463b6168e7829b15d"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-dox-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
