{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-events/2.0.2-jitsi/ktor-events-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-events",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-2.0.2-jitsi.jar",
          "url": "ktor-events-jvm-2.0.2-jitsi.jar",
          "size": 6432,
          "sha512": "8406da66d124c8f60de9ef8f29744e64579b795681d4d05ff4606a6b36bdd32c47eff17f5bcc8c9ea40394801eb0110096649fe482fd1404a64916bbe7583678",
          "sha256": "6ea5d32f5e5557c5448b192a7707f3e98e6ef1406d9f6cc24d3dd97c0595e8e0",
          "sha1": "b7dfa4c639626e1a02210d6721bee70ec32c75e8",
          "md5": "3e6c965ab916ee799926c12eeaada41d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-2.0.2-jitsi.jar",
          "url": "ktor-events-jvm-2.0.2-jitsi.jar",
          "size": 6432,
          "sha512": "8406da66d124c8f60de9ef8f29744e64579b795681d4d05ff4606a6b36bdd32c47eff17f5bcc8c9ea40394801eb0110096649fe482fd1404a64916bbe7583678",
          "sha256": "6ea5d32f5e5557c5448b192a7707f3e98e6ef1406d9f6cc24d3dd97c0595e8e0",
          "sha1": "b7dfa4c639626e1a02210d6721bee70ec32c75e8",
          "md5": "3e6c965ab916ee799926c12eeaada41d"
        }
      ]
    }
  ]
}
