{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-caching-headers/2.0.2-jitsi/ktor-server-caching-headers-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-caching-headers",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-caching-headers-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-caching-headers-jvm-2.0.2-jitsi.jar",
          "size": 16684,
          "sha512": "0ab548ab2b76d28cf5c5b4e05613a437c46425f618c97929a5866672137509eb93f0c12cb2d295e259370fa70fd9aa9de061a8d5a59e6aac84491247ded551aa",
          "sha256": "ca3eef22ff05b92a59e274f6611e4bc14185fe8ceffb47d82d9b78785e072aa6",
          "sha1": "60bb4238ca7d62525d88c58c04490e53393e2c68",
          "md5": "d11917d7545c9de35dfd190bb85bf591"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-caching-headers-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-caching-headers-jvm-2.0.2-jitsi.jar",
          "size": 16684,
          "sha512": "0ab548ab2b76d28cf5c5b4e05613a437c46425f618c97929a5866672137509eb93f0c12cb2d295e259370fa70fd9aa9de061a8d5a59e6aac84491247ded551aa",
          "sha256": "ca3eef22ff05b92a59e274f6611e4bc14185fe8ceffb47d82d9b78785e072aa6",
          "sha1": "60bb4238ca7d62525d88c58c04490e53393e2c68",
          "md5": "d11917d7545c9de35dfd190bb85bf591"
        }
      ]
    }
  ]
}
