{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-forwarded-header/2.0.2-jitsi/ktor-server-forwarded-header-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-forwarded-header",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-forwarded-header-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-forwarded-header-jvm-2.0.2-jitsi.jar",
          "size": 46277,
          "sha512": "d9cf4decd03c8303f02336b26f86864e081464e6fcd14fb82e4204eb4cd2394d2a28778ac06c3f0fdf79c5d996e170b0277389263d6d6f7f46578e9f3f5dd779",
          "sha256": "704d500c83ec112b1e95f2b2fdb8f4425ff302cc249547ce0da13c24938707dd",
          "sha1": "9682d73a2ac1173141aa6bf10985f28bda0c7c6b",
          "md5": "9eadd1923c6adc396dcf02237381d18b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-forwarded-header-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-forwarded-header-jvm-2.0.2-jitsi.jar",
          "size": 46277,
          "sha512": "d9cf4decd03c8303f02336b26f86864e081464e6fcd14fb82e4204eb4cd2394d2a28778ac06c3f0fdf79c5d996e170b0277389263d6d6f7f46578e9f3f5dd779",
          "sha256": "704d500c83ec112b1e95f2b2fdb8f4425ff302cc249547ce0da13c24938707dd",
          "sha1": "9682d73a2ac1173141aa6bf10985f28bda0c7c6b",
          "md5": "9eadd1923c6adc396dcf02237381d18b"
        }
      ]
    }
  ]
}
