{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-core",
    "version": "4.4.8-jitsi-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "55gr4pkpovd5dd4fmxotu6cy3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-4.jar",
          "url": "smack-core-4.4.8-jitsi-4.jar",
          "size": 668930,
          "sha512": "357dd21e41f08e86d656c8a7317466c9ac121973ba1bc03023bce8866735a75cb0f0ecbde92842d50a68d3ca6010bf4dd18377522c4a7d00c12f12c6b051e11a",
          "sha256": "bef6f5ad62b636b00c5e38bfe945db7ddcbd6de8ccc2cef4a4d7d4039cc6605d",
          "sha1": "02b64e75dd0c7883cd4bdbef3af64f0f91f929a6",
          "md5": "834d9f637910360fccb30bf38411b85a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-4.jar",
          "url": "smack-core-4.4.8-jitsi-4.jar",
          "size": 668930,
          "sha512": "357dd21e41f08e86d656c8a7317466c9ac121973ba1bc03023bce8866735a75cb0f0ecbde92842d50a68d3ca6010bf4dd18377522c4a7d00c12f12c6b051e11a",
          "sha256": "bef6f5ad62b636b00c5e38bfe945db7ddcbd6de8ccc2cef4a4d7d4039cc6605d",
          "sha1": "02b64e75dd0c7883cd4bdbef3af64f0f91f929a6",
          "md5": "834d9f637910360fccb30bf38411b85a"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jxmpp-jid",
              "type": "jar",
              "extension": "jar",
              "classifier": "tests"
            }
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-assertj",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-4-test-fixtures.jar",
          "url": "smack-core-4.4.8-jitsi-4-test-fixtures.jar",
          "size": 27631,
          "sha512": "3a2e7d8c6014cd6e36e4d81aedafaf0b332d77935f864373c1ff21f66d56bc3e0633c95ca941cbf7b8462c239491a42c769046042228a50d26a8117bce457ad2",
          "sha256": "cee79aa7e4faf5f615db23cd21d33f5ad8917a0ec9b9a7ce0a3269edf4a447ea",
          "sha1": "1d7d329bda7863666b570696dfedc0f439d4f79c",
          "md5": "b87db8a431ca3af5967f51e3bd25d20a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-core-test-fixtures",
          "version": "4.4.8-jitsi-4"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-stax",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-xpp3",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jxmpp-jid",
              "type": "jar",
              "extension": "jar",
              "classifier": "tests"
            }
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-assertj",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-4-test-fixtures.jar",
          "url": "smack-core-4.4.8-jitsi-4-test-fixtures.jar",
          "size": 27631,
          "sha512": "3a2e7d8c6014cd6e36e4d81aedafaf0b332d77935f864373c1ff21f66d56bc3e0633c95ca941cbf7b8462c239491a42c769046042228a50d26a8117bce457ad2",
          "sha256": "cee79aa7e4faf5f615db23cd21d33f5ad8917a0ec9b9a7ce0a3269edf4a447ea",
          "sha1": "1d7d329bda7863666b570696dfedc0f439d4f79c",
          "md5": "b87db8a431ca3af5967f51e3bd25d20a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-core-test-fixtures",
          "version": "4.4.8-jitsi-4"
        }
      ]
    }
  ]
}
