{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-im",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-1.jar",
          "url": "smack-im-4.4.8-jitsi-1.jar",
          "size": 77181,
          "sha512": "b433b4f34f8114d3d4f8f11de065ef8f46a39ce9a5adb44f210309d647b27c17518aaf8730bea42ae55ca3d2770593f31473131fbead1fb3ff6b1a87d8c206f0",
          "sha256": "ecb6c81fddf3b06d42579278efb4c790b5bf5b2c30ddc970a58e69687c7fc2a4",
          "sha1": "cadb90c6b4858033df7f41d295e90869070daa33",
          "md5": "f5d960ab574e2263427949d66b16f0e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-1.jar",
          "url": "smack-im-4.4.8-jitsi-1.jar",
          "size": 77181,
          "sha512": "b433b4f34f8114d3d4f8f11de065ef8f46a39ce9a5adb44f210309d647b27c17518aaf8730bea42ae55ca3d2770593f31473131fbead1fb3ff6b1a87d8c206f0",
          "sha256": "ecb6c81fddf3b06d42579278efb4c790b5bf5b2c30ddc970a58e69687c7fc2a4",
          "sha1": "cadb90c6b4858033df7f41d295e90869070daa33",
          "md5": "f5d960ab574e2263427949d66b16f0e7"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-im-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "2de56a9d8245528a4a708a5111c74132d282eb3c2ef9893bad3b51c3638d91cc0478e1cd53d2bb99daa023eba4d8d09f26ea95b12068e2f63de2ead97fec6c39",
          "sha256": "f9049afd61eb538a88410359ebd776aa018f4d59129ff956064cad0f547688e9",
          "sha1": "9b9f7a694b470e3c39fe3886969ead829f87830f",
          "md5": "896adf9ef75070b7efdc4d6876e8c9bd"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-im-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-im-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "2de56a9d8245528a4a708a5111c74132d282eb3c2ef9893bad3b51c3638d91cc0478e1cd53d2bb99daa023eba4d8d09f26ea95b12068e2f63de2ead97fec6c39",
          "sha256": "f9049afd61eb538a88410359ebd776aa018f4d59129ff956064cad0f547688e9",
          "sha1": "9b9f7a694b470e3c39fe3886969ead829f87830f",
          "md5": "896adf9ef75070b7efdc4d6876e8c9bd"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-im-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
