{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-servlet/2.0.2-jitsi/ktor-server-servlet-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-servlet",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-servlet-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-servlet-jvm-2.0.2-jitsi.jar",
          "size": 122557,
          "sha512": "5fdbbdb938f90154ddaff6a221c3895ce70fbc2f13321444bd8a41ccfd0d360a2ca847e1cbc724d9558aa89f51d051f001ddb152d4b0ccc638a21b14f6fe64e2",
          "sha256": "31f6e4d82b444587a4c50a63b9825ecf387fb1f0a8008b7c2b79cd2354e7d7d7",
          "sha1": "bedee67bd350b17b4f7158ff54ccc1d6c55c7087",
          "md5": "bcdebe0eb87074820aec6713a3dcfb08"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-servlet-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-servlet-jvm-2.0.2-jitsi.jar",
          "size": 122557,
          "sha512": "5fdbbdb938f90154ddaff6a221c3895ce70fbc2f13321444bd8a41ccfd0d360a2ca847e1cbc724d9558aa89f51d051f001ddb152d4b0ccc638a21b14f6fe64e2",
          "sha256": "31f6e4d82b444587a4c50a63b9825ecf387fb1f0a8008b7c2b79cd2354e7d7d7",
          "sha1": "bedee67bd350b17b4f7158ff54ccc1d6c55c7087",
          "md5": "bcdebe0eb87074820aec6713a3dcfb08"
        }
      ]
    }
  ]
}
