{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-streammanagement",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-streammanagement-4.4.8-jitsi-3.jar",
          "url": "smack-streammanagement-4.4.8-jitsi-3.jar",
          "size": 34949,
          "sha512": "90bb1e2d4bf7fc27ccb3321649916f66f4d0d5ae06fae3a63df00c27050f05348aeb90e74eec3d682cecc8c57a654d5660d96665c1be465b4e715055bc9df933",
          "sha256": "4dbcba958898ed4133d80a0be1d28fb776209852b0950d233855aba66deaff8d",
          "sha1": "a73c01bd284fa11888ece39b8d81b737b2e2b24d",
          "md5": "09bb3f941d71b393f49f50572b47d568"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-streammanagement-4.4.8-jitsi-3.jar",
          "url": "smack-streammanagement-4.4.8-jitsi-3.jar",
          "size": 34949,
          "sha512": "90bb1e2d4bf7fc27ccb3321649916f66f4d0d5ae06fae3a63df00c27050f05348aeb90e74eec3d682cecc8c57a654d5660d96665c1be465b4e715055bc9df933",
          "sha256": "4dbcba958898ed4133d80a0be1d28fb776209852b0950d233855aba66deaff8d",
          "sha1": "a73c01bd284fa11888ece39b8d81b737b2e2b24d",
          "md5": "09bb3f941d71b393f49f50572b47d568"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-streammanagement",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-streammanagement-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-streammanagement-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "f4be34f8af732133c0fd616eaaf7514fe51f288817a715cdce71bb723399e6f3837dbbfdb9f9dcac98356f18529d2366a5915ceb5816514fc765697206b46667",
          "sha256": "fe1bb9ec274f7486eb80ff81d13d69550db5634dcb19220ebda81a8976687af4",
          "sha1": "cbabe7cbb994ec93852c1ef11aebf335b8daf510",
          "md5": "9cd97f45c3ab35994933f8d4fa0e0da7"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-streammanagement-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-streammanagement",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-streammanagement-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-streammanagement-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "f4be34f8af732133c0fd616eaaf7514fe51f288817a715cdce71bb723399e6f3837dbbfdb9f9dcac98356f18529d2366a5915ceb5816514fc765697206b46667",
          "sha256": "fe1bb9ec274f7486eb80ff81d13d69550db5634dcb19220ebda81a8976687af4",
          "sha1": "cbabe7cbb994ec93852c1ef11aebf335b8daf510",
          "md5": "9cd97f45c3ab35994933f8d4fa0e0da7"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-streammanagement-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
