{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-core",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-1.jar",
          "url": "smack-core-4.4.8-jitsi-1.jar",
          "size": 667209,
          "sha512": "9b9cfbc721a31dd67c00356bb4abdb2268e50ac85021ef1f4bd78cfc7e9f1dfa16ed2e357127da29d38e198955d131e67fe918d8b1cbb836237e991bbd80b5aa",
          "sha256": "754083532ecb34ba092d4c3040396c97b0d1ccfd5fe49cd25f8a27803e50eb01",
          "sha1": "ee550aa93fb2559e6131a0fc96eb394b16ad3cb8",
          "md5": "072cbe13df28d835218b82e2872d1fe4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-core",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-1.jar",
          "url": "smack-core-4.4.8-jitsi-1.jar",
          "size": 667209,
          "sha512": "9b9cfbc721a31dd67c00356bb4abdb2268e50ac85021ef1f4bd78cfc7e9f1dfa16ed2e357127da29d38e198955d131e67fe918d8b1cbb836237e991bbd80b5aa",
          "sha256": "754083532ecb34ba092d4c3040396c97b0d1ccfd5fe49cd25f8a27803e50eb01",
          "sha1": "ee550aa93fb2559e6131a0fc96eb394b16ad3cb8",
          "md5": "072cbe13df28d835218b82e2872d1fe4"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jxmpp-jid",
              "type": "jar",
              "extension": "jar",
              "classifier": "tests"
            }
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-assertj",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-core-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 27631,
          "sha512": "242b2917cf518d36f6dbf15876a52ea95c8d1591890ebcba208e6214e436081beb205fcd67073e2c504060f8944b11fab45c97dcd7661d6619dbbf9602b6353f",
          "sha256": "13363c060479d51730292d178daa0462b1c87b8081ddd12b73adf4e4fcec5965",
          "sha1": "8e266c70e69828547b010700bfe2f8764f8a18b4",
          "md5": "05d0fe2d43ac7320d80edc8fd8908a93"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-core-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-stax",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-xpp3",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.65"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.10"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-jid",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jxmpp-jid",
              "type": "jar",
              "extension": "jar",
              "classifier": "tests"
            }
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.11.1"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-assertj",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest-library",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.2-jre"
          }
        }
      ],
      "files": [
        {
          "name": "smack-core-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-core-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 27631,
          "sha512": "242b2917cf518d36f6dbf15876a52ea95c8d1591890ebcba208e6214e436081beb205fcd67073e2c504060f8944b11fab45c97dcd7661d6619dbbf9602b6353f",
          "sha256": "13363c060479d51730292d178daa0462b1c87b8081ddd12b73adf4e4fcec5965",
          "sha1": "8e266c70e69828547b010700bfe2f8764f8a18b4",
          "md5": "05d0fe2d43ac7320d80edc8fd8908a93"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-core-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
