{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-io/2.0.2-jitsi/ktor-io-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-io",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-jvm-2.0.2-jitsi.jar",
          "url": "ktor-io-jvm-2.0.2-jitsi.jar",
          "size": 797651,
          "sha512": "a28c866e4489f1ab6ee8629d7fa848e13858b95cd4dea075a11d340f9bbac5d1cf12f8e920b5ccf4cd923095eebed03fbe34b270f5219679a4485668b300b1e4",
          "sha256": "97d196acf7a3046b43cf49d6368aa8f55c7ae1f06a7c55c69b5aa583c7dfa1dc",
          "sha1": "66399b761d6736f4b3978921309de78b6f982aac",
          "md5": "27c5f547a013fd391c5235ed57ffebad"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-jvm-2.0.2-jitsi.jar",
          "url": "ktor-io-jvm-2.0.2-jitsi.jar",
          "size": 797651,
          "sha512": "a28c866e4489f1ab6ee8629d7fa848e13858b95cd4dea075a11d340f9bbac5d1cf12f8e920b5ccf4cd923095eebed03fbe34b270f5219679a4485668b300b1e4",
          "sha256": "97d196acf7a3046b43cf49d6368aa8f55c7ae1f06a7c55c69b5aa583c7dfa1dc",
          "sha1": "66399b761d6736f4b3978921309de78b6f982aac",
          "md5": "27c5f547a013fd391c5235ed57ffebad"
        }
      ]
    }
  ]
}
