{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-javax",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-1.jar",
          "size": 4273,
          "sha512": "31e6db376c1cd370c269671383df5c800899cf81ef97b338b5e90d4a35f5d9089f2aadb0501526031df99c16d68c084fabe41f8bdac5e94127bbba39f210f1d8",
          "sha256": "a1852ed95788a1cc417c46242ee8ec612b06b7a851f30fe8ee9b406baa59e9ff",
          "sha1": "dd609e06f65de22a8bf00b0f47d1d90a3787574e",
          "md5": "b060f58e6ea793b0583b48998cde8d7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-1.jar",
          "size": 4273,
          "sha512": "31e6db376c1cd370c269671383df5c800899cf81ef97b338b5e90d4a35f5d9089f2aadb0501526031df99c16d68c084fabe41f8bdac5e94127bbba39f210f1d8",
          "sha256": "a1852ed95788a1cc417c46242ee8ec612b06b7a851f30fe8ee9b406baa59e9ff",
          "sha1": "dd609e06f65de22a8bf00b0f47d1d90a3787574e",
          "md5": "b060f58e6ea793b0583b48998cde8d7f"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-javax",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-javax-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-javax",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-javax-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
