{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-bosh",
    "version": "4.4.8-jitsi-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "55gr4pkpovd5dd4fmxotu6cy3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.jbosh",
          "module": "jbosh",
          "version": {
            "requires": "[0.9.1,0.9.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-4.jar",
          "url": "smack-bosh-4.4.8-jitsi-4.jar",
          "size": 17878,
          "sha512": "eec622bd0ad2f8e13210d85edf7450f6676336cc7b86316f4739ef41de27309c1c39770ffc1ad2ef4f12fee2147042a2ee5158525d746bd0f4a9ffefcdaeca2f",
          "sha256": "37dbe00850cc9ca4db55ec3ed239e7e851232f963732f6f897eeb5a7faec7e6c",
          "sha1": "dd16272c7c487f15467e3f1b910057cde09c1e2c",
          "md5": "2382cc65eead559716a4649ae5944d6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.jbosh",
          "module": "jbosh",
          "version": {
            "requires": "[0.9.1,0.9.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-4.jar",
          "url": "smack-bosh-4.4.8-jitsi-4.jar",
          "size": 17878,
          "sha512": "eec622bd0ad2f8e13210d85edf7450f6676336cc7b86316f4739ef41de27309c1c39770ffc1ad2ef4f12fee2147042a2ee5158525d746bd0f4a9ffefcdaeca2f",
          "sha256": "37dbe00850cc9ca4db55ec3ed239e7e851232f963732f6f897eeb5a7faec7e6c",
          "sha1": "dd16272c7c487f15467e3f1b910057cde09c1e2c",
          "md5": "2382cc65eead559716a4649ae5944d6c"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-4-test-fixtures.jar",
          "url": "smack-bosh-4.4.8-jitsi-4-test-fixtures.jar",
          "size": 261,
          "sha512": "0ea3237d07e11dc8b3f0c639125105deb2f846350ede3fc372bc8fa2add4b7f8ff488acc09fd3d128e29beafd4931cf37b6e9d6dcf3530986c0faaed68b7499b",
          "sha256": "33604ffc4a490e5e4522ab099a460e00c61b631b25597a6b9936905b2f962a07",
          "sha1": "7d2bd054d87700e8138ecc60c0e835c65974faff",
          "md5": "96582c565e5baf529eca7b9758aa77e1"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-bosh-test-fixtures",
          "version": "4.4.8-jitsi-4"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-4-test-fixtures.jar",
          "url": "smack-bosh-4.4.8-jitsi-4-test-fixtures.jar",
          "size": 261,
          "sha512": "0ea3237d07e11dc8b3f0c639125105deb2f846350ede3fc372bc8fa2add4b7f8ff488acc09fd3d128e29beafd4931cf37b6e9d6dcf3530986c0faaed68b7499b",
          "sha256": "33604ffc4a490e5e4522ab099a460e00c61b631b25597a6b9936905b2f962a07",
          "sha1": "7d2bd054d87700e8138ecc60c0e835c65974faff",
          "md5": "96582c565e5baf529eca7b9758aa77e1"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-bosh-test-fixtures",
          "version": "4.4.8-jitsi-4"
        }
      ]
    }
  ]
}
