{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-android/2.0.2-jitsi/ktor-client-android-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-android",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-android-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-android-jvm-2.0.2-jitsi.jar",
          "size": 28631,
          "sha512": "aa5024692d62fcf1a0407dc87a62265fc1a457aa227771b7b42d951da66bf3f3f77dc2567ac63a0f6a5106b4ea0269eb4a086fcbcd46d609752eb50210acc7de",
          "sha256": "85238f0881a32c2208a7100a439849618d3bf52971f6ea48321c8614999e10c5",
          "sha1": "4d91e2ebde9a84eca5691225b817b09dd67202a0",
          "md5": "87ff1396af31248f107434c40e60033b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-android-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-android-jvm-2.0.2-jitsi.jar",
          "size": 28631,
          "sha512": "aa5024692d62fcf1a0407dc87a62265fc1a457aa227771b7b42d951da66bf3f3f77dc2567ac63a0f6a5106b4ea0269eb4a086fcbcd46d609752eb50210acc7de",
          "sha256": "85238f0881a32c2208a7100a439849618d3bf52971f6ea48321c8614999e10c5",
          "sha1": "4d91e2ebde9a84eca5691225b817b09dd67202a0",
          "md5": "87ff1396af31248f107434c40e60033b"
        }
      ]
    }
  ]
}
