{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-omemo-signal-integration-test",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-signal-integration-test-4.4.8-jitsi-1.jar",
          "url": "smack-omemo-signal-integration-test-4.4.8-jitsi-1.jar",
          "size": 2476,
          "sha512": "160f6b5cdd7c94b22b95834a55881ba45ef9b817c79b0e10cfdf10438b2220bc51c6b0be536036a190631b4bc0be7aa1d235ee1588e8d23d59073510eeab167a",
          "sha256": "cad343498030dca5bff73f3aeb452c0a941a970c863505f6ec3d5b4d39a91fa6",
          "sha1": "20bac29977d35ceb0de7e9126cce27ece9701642",
          "md5": "ad327c85f7a2e8be9c3810319603f499"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-signal-integration-test-4.4.8-jitsi-1.jar",
          "url": "smack-omemo-signal-integration-test-4.4.8-jitsi-1.jar",
          "size": 2476,
          "sha512": "160f6b5cdd7c94b22b95834a55881ba45ef9b817c79b0e10cfdf10438b2220bc51c6b0be536036a190631b4bc0be7aa1d235ee1588e8d23d59073510eeab167a",
          "sha256": "cad343498030dca5bff73f3aeb452c0a941a970c863505f6ec3d5b4d39a91fa6",
          "sha1": "20bac29977d35ceb0de7e9126cce27ece9701642",
          "md5": "ad327c85f7a2e8be9c3810319603f499"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-signal-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-omemo-signal-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "35f73918b5e2150e40358f3734f541e892baded5fc52b72d06cffc0a134cf2603824a0b81f17ada728a8471b1636888bdbcbcbb32352671af37325251a17b900",
          "sha256": "779391db975d182b969566cb6751f7fc84056c7ad74fbb2ab54474751f533975",
          "sha1": "76d5bb5501a1bf1a6863767fa181158b91724aa8",
          "md5": "331879f836075be3491dce1955683763"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-omemo-signal-integration-test-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-signal-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-omemo-signal-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "35f73918b5e2150e40358f3734f541e892baded5fc52b72d06cffc0a134cf2603824a0b81f17ada728a8471b1636888bdbcbcbb32352671af37325251a17b900",
          "sha256": "779391db975d182b969566cb6751f7fc84056c7ad74fbb2ab54474751f533975",
          "sha1": "76d5bb5501a1bf1a6863767fa181158b91724aa8",
          "md5": "331879f836075be3491dce1955683763"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-omemo-signal-integration-test-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
