{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-conditional-headers/2.0.2-jitsi/ktor-server-conditional-headers-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-conditional-headers",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-conditional-headers-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-conditional-headers-jvm-2.0.2-jitsi.jar",
          "size": 21063,
          "sha512": "79b3299c3e3484e4fed8845cf8affc42de1b2fe4e383ed1b3e79e48c51bc1ff0c816bf823e3ae90bc458ec71e3ec8e70a3f78cf6c582c0cfaa2e56c17915996b",
          "sha256": "66099a3451cc1f65e10e59b2a8624ea4f4b5d286699fa0f13422d1609285a3b7",
          "sha1": "d98eee4902a2e18c7371d1403ce00f9173b8edf4",
          "md5": "66369c52cd1f190dfe3591188a7c68d0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-conditional-headers-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-conditional-headers-jvm-2.0.2-jitsi.jar",
          "size": 21063,
          "sha512": "79b3299c3e3484e4fed8845cf8affc42de1b2fe4e383ed1b3e79e48c51bc1ff0c816bf823e3ae90bc458ec71e3ec8e70a3f78cf6c582c0cfaa2e56c17915996b",
          "sha256": "66099a3451cc1f65e10e59b2a8624ea4f4b5d286699fa0f13422d1609285a3b7",
          "sha1": "d98eee4902a2e18c7371d1403ce00f9173b8edf4",
          "md5": "66369c52cd1f190dfe3591188a7c68d0"
        }
      ]
    }
  ]
}
