{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-pebble/2.0.2-jitsi/ktor-server-pebble-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-pebble",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.pebbletemplates",
          "module": "pebble",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-pebble-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-pebble-jvm-2.0.2-jitsi.jar",
          "size": 11747,
          "sha512": "f120dee604cca4431790e310a24581ee4b8f63dac85e95a23e1b04cf6d98c37127fbab39c539817962d54b96f07c5abe1f89bc5eb8b4107285044c851869cc36",
          "sha256": "c41eb3d9b8e8770500fe2e78f8e228cf1ca44c89fc6ff49050c7ec5f54cee41c",
          "sha1": "4ea53bf3236434b7567ea31086699c2ecf6bd49e",
          "md5": "66c26ac376b6bc5f2963518d31e244a3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.pebbletemplates",
          "module": "pebble",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-pebble-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-pebble-jvm-2.0.2-jitsi.jar",
          "size": 11747,
          "sha512": "f120dee604cca4431790e310a24581ee4b8f63dac85e95a23e1b04cf6d98c37127fbab39c539817962d54b96f07c5abe1f89bc5eb8b4107285044c851869cc36",
          "sha256": "c41eb3d9b8e8770500fe2e78f8e228cf1ca44c89fc6ff49050c7ec5f54cee41c",
          "sha1": "4ea53bf3236434b7567ea31086699c2ecf6bd49e",
          "md5": "66c26ac376b6bc5f2963518d31e244a3"
        }
      ]
    }
  ]
}
