{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-dnsjava",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "[3.0.0,3.0.9999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-3.jar",
          "size": 3409,
          "sha512": "769f79a9a9447be2e5b90425dea9d55c36810d95e0689d9570be814e5fc0e0fa44dd24a9f7ec0e08ff1f1d650724843c2440ecec290e1b12a9c0f60b30f8a2ce",
          "sha256": "ec4e30f680cc3c937e44c447b405d76fd4e0382706f4a4e7294295f6207edb36",
          "sha1": "8c6b3dc712a449fb8731d00af762dc1f1cb55c79",
          "md5": "bc93a243208c92d9869ddf3b4343ce89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "[3.0.0,3.0.9999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-3.jar",
          "size": 3409,
          "sha512": "769f79a9a9447be2e5b90425dea9d55c36810d95e0689d9570be814e5fc0e0fa44dd24a9f7ec0e08ff1f1d650724843c2440ecec290e1b12a9c0f60b30f8a2ce",
          "sha256": "ec4e30f680cc3c937e44c447b405d76fd4e0382706f4a4e7294295f6207edb36",
          "sha1": "8c6b3dc712a449fb8731d00af762dc1f1cb55c79",
          "md5": "bc93a243208c92d9869ddf3b4343ce89"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-dnsjava",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "a108bbad98d32839bca2df9ebb8e709eb8c8bddaaf2ea86cd4acc61275bf2a7c9108cb2c84cf69e04295c3333d5cfdb597431a6d2a1a5d5a3aaa018a087f46dc",
          "sha256": "abb80c93547d47f9ddebf1b42484e63596f21a08349bc8c304e3657e40bc4187",
          "sha1": "203e60f08bbeb55633f724e7dd534a3a9b5b9a73",
          "md5": "3fb23e27c9c42f37c409f071f9dd370a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-dnsjava-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-dnsjava",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "a108bbad98d32839bca2df9ebb8e709eb8c8bddaaf2ea86cd4acc61275bf2a7c9108cb2c84cf69e04295c3333d5cfdb597431a6d2a1a5d5a3aaa018a087f46dc",
          "sha256": "abb80c93547d47f9ddebf1b42484e63596f21a08349bc8c304e3657e40bc4187",
          "sha1": "203e60f08bbeb55633f724e7dd534a3a9b5b9a73",
          "md5": "3fb23e27c9c42f37c409f071f9dd370a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-dnsjava-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
