{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-call-logging/2.0.2-jitsi/ktor-server-call-logging-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-call-logging",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-call-logging-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-call-logging-jvm-2.0.2-jitsi.jar",
          "size": 53374,
          "sha512": "c9b39a86d527c4dc5ec4fb69f819eff39d3dff176fafe449d4ed8ad5dd301b6de192cf0c84b4a35b2564c98d67e30eef67a365ab8db51bd130c4e7a8ab261095",
          "sha256": "ae7ae5708a3fe62dbb935ccccb86ff62222f01c0cda81a3541885f0f1697c627",
          "sha1": "cc38c0e0f29d182ddac347a4d0def29585894975",
          "md5": "bc6a4f0e4adefc41e1c399ac902950a1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-slf4j",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-call-logging-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-call-logging-jvm-2.0.2-jitsi.jar",
          "size": 53374,
          "sha512": "c9b39a86d527c4dc5ec4fb69f819eff39d3dff176fafe449d4ed8ad5dd301b6de192cf0c84b4a35b2564c98d67e30eef67a365ab8db51bd130c4e7a8ab261095",
          "sha256": "ae7ae5708a3fe62dbb935ccccb86ff62222f01c0cda81a3541885f0f1697c627",
          "sha1": "cc38c0e0f29d182ddac347a4d0def29585894975",
          "md5": "bc6a4f0e4adefc41e1c399ac902950a1"
        }
      ]
    }
  ]
}
