{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-logging/2.0.2-jitsi/ktor-client-logging-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-logging",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-logging-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-logging-jvm-2.0.2-jitsi.jar",
          "size": 56427,
          "sha512": "1adf53dd4683a3ea286219071ddacaa35502c8cde35c61ae9bc03ff25cb8a8dbb900d867698c62cea24dd2e34e80e8b0963f0b49870a376d58f754e2e58116ac",
          "sha256": "3640cbe64c4546d9dab6b6de1a09a4cbaa7e6a27dbad53b8eb53d54dac6b86fc",
          "sha1": "c2f06312a8a4d342a209fc07c3d29342ff6985ec",
          "md5": "9b079fefcc5ebded1d4b98af410f5cb4"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-logging-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-logging-jvm-2.0.2-jitsi.jar",
          "size": 56427,
          "sha512": "1adf53dd4683a3ea286219071ddacaa35502c8cde35c61ae9bc03ff25cb8a8dbb900d867698c62cea24dd2e34e80e8b0963f0b49870a376d58f754e2e58116ac",
          "sha256": "3640cbe64c4546d9dab6b6de1a09a4cbaa7e6a27dbad53b8eb53d54dac6b86fc",
          "sha1": "c2f06312a8a4d342a209fc07c3d29342ff6985ec",
          "md5": "9b079fefcc5ebded1d4b98af410f5cb4"
        }
      ]
    }
  ]
}
