{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-java8-full",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-1.jar",
          "url": "smack-java8-full-4.4.8-jitsi-1.jar",
          "size": 2645,
          "sha512": "e13ca52cd629d343877ab385294ccacb7cdb6217e9b858fb69b662fd293a185ccc9cd6c85a17904327472d8ef967b0cf0fc2559ac168c84985958f9b3364a073",
          "sha256": "8c771070395079c2496765fa62d78cf01737db617b81343f57874f3cb5c60270",
          "sha1": "789bdd067310a7d12100932f7a6c7b7c32fbffa8",
          "md5": "db95db55499cc3245897a2562d67b0a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-1.jar",
          "url": "smack-java8-full-4.4.8-jitsi-1.jar",
          "size": 2645,
          "sha512": "e13ca52cd629d343877ab385294ccacb7cdb6217e9b858fb69b662fd293a185ccc9cd6c85a17904327472d8ef967b0cf0fc2559ac168c84985958f9b3364a073",
          "sha256": "8c771070395079c2496765fa62d78cf01737db617b81343f57874f3cb5c60270",
          "sha1": "789bdd067310a7d12100932f7a6c7b7c32fbffa8",
          "md5": "db95db55499cc3245897a2562d67b0a1"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "ffcac395826b18d1050106bc9117a675ff5271dc5772858c835c950661e3e464bad21e5528f2fdbf039c01fffbf46e4306d70acffb67a585f8558792afd4c95b",
          "sha256": "4d3d6de3990d540c6ab9cfe299de8234ae30de33a2d9bda0b2474263c2da7c54",
          "sha1": "9f2e827a2c0aa8b108f1cd2b4beadb822049b1ca",
          "md5": "a7aed10740c5e7099f725bd133abfe07"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "ffcac395826b18d1050106bc9117a675ff5271dc5772858c835c950661e3e464bad21e5528f2fdbf039c01fffbf46e4306d70acffb67a585f8558792afd4c95b",
          "sha256": "4d3d6de3990d540c6ab9cfe299de8234ae30de33a2d9bda0b2474263c2da7c54",
          "sha1": "9f2e827a2c0aa8b108f1cd2b4beadb822049b1ca",
          "md5": "a7aed10740c5e7099f725bd133abfe07"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
