{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-sasl-provided",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-1.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-1.jar",
          "size": 10715,
          "sha512": "a6925ccf2e349377eaac18f11b0caf39d3e7a1e721a2dc692e07baec473a5c72a9cb6048ee6759fee4eac66fc9c4262a37ae49911495b2aa5ea8314a5657acdc",
          "sha256": "e1751876ee03071955880c1ad45640fe5348e86d9b172765d7b2beaf8d18fd46",
          "sha1": "5121961f0d09a2ae980fa28a57f018396cc29191",
          "md5": "45d946a427b245b6403cf03e710cd03d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-1.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-1.jar",
          "size": 10715,
          "sha512": "a6925ccf2e349377eaac18f11b0caf39d3e7a1e721a2dc692e07baec473a5c72a9cb6048ee6759fee4eac66fc9c4262a37ae49911495b2aa5ea8314a5657acdc",
          "sha256": "e1751876ee03071955880c1ad45640fe5348e86d9b172765d7b2beaf8d18fd46",
          "sha1": "5121961f0d09a2ae980fa28a57f018396cc29191",
          "md5": "45d946a427b245b6403cf03e710cd03d"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-sasl-provided",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "54413d54d5d4b4f8c439f6bdb283753c66ad3700f5ea358348a05df8b9d13d66be33d11b6499bacb462c03585460a79ef42254e415367db578b03a9897a00fb2",
          "sha256": "210c3b750600f174b43d029dc9392facd9260b07d5185bc137524790dce00ae5",
          "sha1": "6deea55da4934e12e24563520214b96e129c160a",
          "md5": "d08aaecbad670204eeda1976fd78cdac"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-sasl-provided-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-sasl-provided",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "54413d54d5d4b4f8c439f6bdb283753c66ad3700f5ea358348a05df8b9d13d66be33d11b6499bacb462c03585460a79ef42254e415367db578b03a9897a00fb2",
          "sha256": "210c3b750600f174b43d029dc9392facd9260b07d5185bc137524790dce00ae5",
          "sha1": "6deea55da4934e12e24563520214b96e129c160a",
          "md5": "d08aaecbad670204eeda1976fd78cdac"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-sasl-provided-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
