{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-im",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-3.jar",
          "url": "smack-im-4.4.8-jitsi-3.jar",
          "size": 77181,
          "sha512": "04227b6d17a83158213946d2aa8fff6d78b0f6d1320de19f1958d403bf55821fc08d7d7ca46ce064596b8db8d17734a3b5fc7fd6151f1ac8ecc2a4c9b4f66faf",
          "sha256": "4811af10bd726c7e3919d3d4aa58001b3fc7a09aab1ed9ad03f458b722a71a70",
          "sha1": "e2d77e3cddb000f96b78e1d4518747af3d224b01",
          "md5": "2313a0c225437b7619fd664475c12da0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-3.jar",
          "url": "smack-im-4.4.8-jitsi-3.jar",
          "size": 77181,
          "sha512": "04227b6d17a83158213946d2aa8fff6d78b0f6d1320de19f1958d403bf55821fc08d7d7ca46ce064596b8db8d17734a3b5fc7fd6151f1ac8ecc2a4c9b4f66faf",
          "sha256": "4811af10bd726c7e3919d3d4aa58001b3fc7a09aab1ed9ad03f458b722a71a70",
          "sha1": "e2d77e3cddb000f96b78e1d4518747af3d224b01",
          "md5": "2313a0c225437b7619fd664475c12da0"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-im-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "4a209adb94440db02d4fc03f1f46b63f63a359a17a42ef291b46a49b12992bc7a9028f36656ec1f9941ab00c3bcd63cace4e30a0902ed977d55307be314aee0b",
          "sha256": "0cd7460244d4b77809e382b2cae30be4553bac4393b3e84f7c78f9a6ca0a5113",
          "sha1": "3684e7b022f47f653c5f5e10a2355f16f895f5ee",
          "md5": "2d5f9c0bda9c59b973efdd7b6c9b8df1"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-im-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-im-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-im-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "4a209adb94440db02d4fc03f1f46b63f63a359a17a42ef291b46a49b12992bc7a9028f36656ec1f9941ab00c3bcd63cace4e30a0902ed977d55307be314aee0b",
          "sha256": "0cd7460244d4b77809e382b2cae30be4553bac4393b3e84f7c78f9a6ca0a5113",
          "sha1": "3684e7b022f47f653c5f5e10a2355f16f895f5ee",
          "md5": "2d5f9c0bda9c59b973efdd7b6c9b8df1"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-im-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
