{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-plugins/2.0.2-jitsi/ktor-client-plugins-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-plugins",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-plugins-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-plugins-jvm-2.0.2-jitsi.jar",
          "size": 345,
          "sha512": "cd13877aac0e11c11d6805e62fffd188f8426d061080c07c027de954098f62e2c9cfb87495cf4203a4f621f56ce0b1f58a5ffc6fccfb360f44d30085f11aa6e8",
          "sha256": "889786dc930e321ebbb13a0bf023572c44c33736b6704e3037d42109fd8a6604",
          "sha1": "8805488e4e5200e9518e4b1f6e5231fb6bf367be",
          "md5": "0659283d55ed3a447f40dd1e76ddb131"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-plugins-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-plugins-jvm-2.0.2-jitsi.jar",
          "size": 345,
          "sha512": "cd13877aac0e11c11d6805e62fffd188f8426d061080c07c027de954098f62e2c9cfb87495cf4203a4f621f56ce0b1f58a5ffc6fccfb360f44d30085f11aa6e8",
          "sha256": "889786dc930e321ebbb13a0bf023572c44c33736b6704e3037d42109fd8a6604",
          "sha1": "8805488e4e5200e9518e4b1f6e5231fb6bf367be",
          "md5": "0659283d55ed3a447f40dd1e76ddb131"
        }
      ]
    }
  ]
}
