{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-java/2.0.2-jitsi/ktor-client-java-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-java",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-java-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-java-jvm-2.0.2-jitsi.jar",
          "size": 78421,
          "sha512": "24bfb656ac6ccc62459a0c24179200a09a0e10a285f902687343c4f6a6a1b9f6022157c167cc80adc14cf35ce6f7ff3a28f7bc8861511041b51a260af5229f19",
          "sha256": "bab252b5591e6414d69dec698c1a06779eeed6f39c8f9a9c39ab365a818216ba",
          "sha1": "a7f44add68ac3fc595ca919cacf7550b584e4c64",
          "md5": "96cb4b4cae948d865704f7ea910616a7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-java-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-java-jvm-2.0.2-jitsi.jar",
          "size": 78421,
          "sha512": "24bfb656ac6ccc62459a0c24179200a09a0e10a285f902687343c4f6a6a1b9f6022157c167cc80adc14cf35ce6f7ff3a28f7bc8861511041b51a260af5229f19",
          "sha256": "bab252b5591e6414d69dec698c1a06779eeed6f39c8f9a9c39ab365a818216ba",
          "sha1": "a7f44add68ac3fc595ca919cacf7550b584e4c64",
          "md5": "96cb4b4cae948d865704f7ea910616a7"
        }
      ]
    }
  ]
}
