{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-minidns",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-hla",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-util-cache",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-1.jar",
          "size": 7658,
          "sha512": "3f542dc38097150053c875c54c8109db168c5f2adf33451f76ad22f0520480a882812fe885d88a7c797dc707638679d7b5a06ad425d16b741c711fbbfeeaf6c3",
          "sha256": "f14ab0d77a5f93126e7048ad91ff906c06cec0cd7e0b32a62964da27a72e3ec8",
          "sha1": "8b93b542160df93c478b7712ebb6583cac943ec6",
          "md5": "f790a97e0abeb24d8e1906d1d70b66a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-hla",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-util-cache",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-1.jar",
          "size": 7658,
          "sha512": "3f542dc38097150053c875c54c8109db168c5f2adf33451f76ad22f0520480a882812fe885d88a7c797dc707638679d7b5a06ad425d16b741c711fbbfeeaf6c3",
          "sha256": "f14ab0d77a5f93126e7048ad91ff906c06cec0cd7e0b32a62964da27a72e3ec8",
          "sha1": "8b93b542160df93c478b7712ebb6583cac943ec6",
          "md5": "f790a97e0abeb24d8e1906d1d70b66a5"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "334934e00304a863f0b4087fb92ce75a7d7307408f3650c257c2c61a35a1f15fa17b51201f23c93c366a4fd54f2f5842c473115ec930cc33cbed817abd5dadec",
          "sha256": "205dc1dc57c736c93a72cbe294f5389c462a309d06b45a89fd07d71b54f99730",
          "sha1": "4a28432ab76f2a401961cfc85851b152bc6052ed",
          "md5": "e37edcd65229a56255b21d7b0f0e4909"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "334934e00304a863f0b4087fb92ce75a7d7307408f3650c257c2c61a35a1f15fa17b51201f23c93c366a4fd54f2f5842c473115ec930cc33cbed817abd5dadec",
          "sha256": "205dc1dc57c736c93a72cbe294f5389c462a309d06b45a89fd07d71b54f99730",
          "sha1": "4a28432ab76f2a401961cfc85851b152bc6052ed",
          "md5": "e37edcd65229a56255b21d7b0f0e4909"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
