{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-android-extensions",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-3.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-3.jar",
          "size": 6253,
          "sha512": "206330868ba689b36c16fc4ab30ad32657fed3923af91074d5b48f41a56abee08e97e91ce8fe094cbb1a17c9e20e57733192acee36d4bdd4a8a1ff5dc4a9d5ef",
          "sha256": "5e60c7998e2e5dc79856727a8310e7c2495355afd9967836902e6a0e87df83b7",
          "sha1": "f35ff8586991d9fe73a28908c5e46735012d4971",
          "md5": "7eaeceb5ea41b5aa8f0f7525283a5e93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-3.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-3.jar",
          "size": 6253,
          "sha512": "206330868ba689b36c16fc4ab30ad32657fed3923af91074d5b48f41a56abee08e97e91ce8fe094cbb1a17c9e20e57733192acee36d4bdd4a8a1ff5dc4a9d5ef",
          "sha256": "5e60c7998e2e5dc79856727a8310e7c2495355afd9967836902e6a0e87df83b7",
          "sha1": "f35ff8586991d9fe73a28908c5e46735012d4971",
          "md5": "7eaeceb5ea41b5aa8f0f7525283a5e93"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "d1781b4e8aa600b4db059504e5375d63345e72421f0f620a05c7d4023ba3892563e01dfa5ff4e04b03998d2e7fea66eb00f0ede787594f320caa6a822d1b766e",
          "sha256": "a53d509a1a8b648e0a192855f14574c3fa7036f6b2bd260cdcca7492b10e4ee3",
          "sha1": "098d6dc03d649e89572bc880322c2083eb677e4f",
          "md5": "b7bf9a5e6997a4b08eb13c07e8fd3952"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-android-extensions-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "d1781b4e8aa600b4db059504e5375d63345e72421f0f620a05c7d4023ba3892563e01dfa5ff4e04b03998d2e7fea66eb00f0ede787594f320caa6a822d1b766e",
          "sha256": "a53d509a1a8b648e0a192855f14574c3fa7036f6b2bd260cdcca7492b10e4ee3",
          "sha1": "098d6dc03d649e89572bc880322c2083eb677e4f",
          "md5": "b7bf9a5e6997a4b08eb13c07e8fd3952"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-android-extensions-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
