{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-omemo",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-3.jar",
          "url": "smack-omemo-4.4.8-jitsi-3.jar",
          "size": 117851,
          "sha512": "3760b81ce449c56fab3a267034c72048b163aa89e17e44cace807f8d23ab85393d6f3b7a55d9ac4e4b514d8ff1d93906177d4b8aa712923e11d9037b3fd82953",
          "sha256": "3dad06fc4525293b590f6afc3a45739624a220e7dece4c8ea9fc7ec83bab8c0b",
          "sha1": "4fb563a33993d4c0946fb27e602e645d8b2d1d12",
          "md5": "4ad3c8b3dc4f663af6853ff3b538333f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-im",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-3.jar",
          "url": "smack-omemo-4.4.8-jitsi-3.jar",
          "size": 117851,
          "sha512": "3760b81ce449c56fab3a267034c72048b163aa89e17e44cace807f8d23ab85393d6f3b7a55d9ac4e4b514d8ff1d93906177d4b8aa712923e11d9037b3fd82953",
          "sha256": "3dad06fc4525293b590f6afc3a45739624a220e7dece4c8ea9fc7ec83bab8c0b",
          "sha1": "4fb563a33993d4c0946fb27e602e645d8b2d1d12",
          "md5": "4ad3c8b3dc4f663af6853ff3b538333f"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-omemo-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "15aae35d55dc177de102de420df83127c86b1b17eb56fc93eb54c93e7bc922e155d8f6b3dd6a58fbb25a93b48eaa9f9305d5f209ca6ad9e6af333bd2d7c47cd7",
          "sha256": "32567f031d70165ed383c976a4f77958d9889b1ac02502a68c5b0a67e11010db",
          "sha1": "f1f66f8c51dcca5c5213286af64a5a33b5d246ff",
          "md5": "27297bee7b7fc6dced975a6c5ea7e8dc"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-omemo-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-omemo-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-omemo-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "15aae35d55dc177de102de420df83127c86b1b17eb56fc93eb54c93e7bc922e155d8f6b3dd6a58fbb25a93b48eaa9f9305d5f209ca6ad9e6af333bd2d7c47cd7",
          "sha256": "32567f031d70165ed383c976a4f77958d9889b1ac02502a68c5b0a67e11010db",
          "sha1": "f1f66f8c51dcca5c5213286af64a5a33b5d246ff",
          "md5": "27297bee7b7fc6dced975a6c5ea7e8dc"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-omemo-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
