{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-minidns-dox",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-1.jar",
          "size": 2602,
          "sha512": "cb75ed1b6cf484c3af7713dbe653a4df8720a3746f51ac02968a7c5c9706782e53b180316e092d1e94859f6598038f70fce8bcd78d8111fb4ace9f756b443691",
          "sha256": "8f32dd0a031d8eb95fc8019d6966ec372f50e4b411821747e0ca6af4aba3c627",
          "sha1": "e7860f3b193d20a3d2b473207b8b1b3fe132bd12",
          "md5": "b3e341d3c9d50fb8ad3f05b821ef3d07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-1.jar",
          "size": 2602,
          "sha512": "cb75ed1b6cf484c3af7713dbe653a4df8720a3746f51ac02968a7c5c9706782e53b180316e092d1e94859f6598038f70fce8bcd78d8111fb4ace9f756b443691",
          "sha256": "8f32dd0a031d8eb95fc8019d6966ec372f50e4b411821747e0ca6af4aba3c627",
          "sha1": "e7860f3b193d20a3d2b473207b8b1b3fe132bd12",
          "md5": "b3e341d3c9d50fb8ad3f05b821ef3d07"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "334934e00304a863f0b4087fb92ce75a7d7307408f3650c257c2c61a35a1f15fa17b51201f23c93c366a4fd54f2f5842c473115ec930cc33cbed817abd5dadec",
          "sha256": "205dc1dc57c736c93a72cbe294f5389c462a309d06b45a89fd07d71b54f99730",
          "sha1": "4a28432ab76f2a401961cfc85851b152bc6052ed",
          "md5": "e37edcd65229a56255b21d7b0f0e4909"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-dox-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-dox-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-minidns-dox-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "334934e00304a863f0b4087fb92ce75a7d7307408f3650c257c2c61a35a1f15fa17b51201f23c93c366a4fd54f2f5842c473115ec930cc33cbed817abd5dadec",
          "sha256": "205dc1dc57c736c93a72cbe294f5389c462a309d06b45a89fd07d71b54f99730",
          "sha1": "4a28432ab76f2a401961cfc85851b152bc6052ed",
          "md5": "e37edcd65229a56255b21d7b0f0e4909"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-dox-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
