{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-test-dispatcher/2.0.2-jitsi/ktor-test-dispatcher-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-test-dispatcher",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-jvm-2.0.2-jitsi.jar",
          "url": "ktor-test-dispatcher-jvm-2.0.2-jitsi.jar",
          "size": 3840,
          "sha512": "202ab528f2051ff52c5c5a2d1192a2e16b8f5b70c3f8118379f016453eccbf4a704ffe45fab5df0413bf25197fd264e6f41a066524b3696bcc87d1f525927688",
          "sha256": "0622c1215c9bfa46d2cbbfcb75a10c56e541fe32b9ebaf179e4005fb62c6fe3b",
          "sha1": "1dddd2085d6adc80d50f69eaf5b4c05d912f36d5",
          "md5": "2abd4879ad7fab8dc5788ef77b8803e5"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-test-dispatcher-jvm-2.0.2-jitsi.jar",
          "url": "ktor-test-dispatcher-jvm-2.0.2-jitsi.jar",
          "size": 3840,
          "sha512": "202ab528f2051ff52c5c5a2d1192a2e16b8f5b70c3f8118379f016453eccbf4a704ffe45fab5df0413bf25197fd264e6f41a066524b3696bcc87d1f525927688",
          "sha256": "0622c1215c9bfa46d2cbbfcb75a10c56e541fe32b9ebaf179e4005fb62c6fe3b",
          "sha1": "1dddd2085d6adc80d50f69eaf5b4c05d912f36d5",
          "md5": "2abd4879ad7fab8dc5788ef77b8803e5"
        }
      ]
    }
  ]
}
