{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-freemarker/2.0.2-jitsi/ktor-server-freemarker-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-freemarker",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-freemarker-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-freemarker-jvm-2.0.2-jitsi.jar",
          "size": 11688,
          "sha512": "618ac3adf5e057d7a471598225e9541236d169a4c9d0c8acf160552cbb5db193c7475d91e1565558a57fd3dbfe2386e3a9c2c3777cd40f4fdea65aaf522c79ee",
          "sha256": "0142e5e490ba0d0dcdca4152e9ee9ed2e2594e647d3d9e1d422773417800aea1",
          "sha1": "5f65fd322d8c0645d99b82cbc9ed489204a57ec4",
          "md5": "09b17d43c7cfe7b0b9e3e517c9dda36a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.freemarker",
          "module": "freemarker",
          "version": {
            "requires": "2.3.31"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-freemarker-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-freemarker-jvm-2.0.2-jitsi.jar",
          "size": 11688,
          "sha512": "618ac3adf5e057d7a471598225e9541236d169a4c9d0c8acf160552cbb5db193c7475d91e1565558a57fd3dbfe2386e3a9c2c3777cd40f4fdea65aaf522c79ee",
          "sha256": "0142e5e490ba0d0dcdca4152e9ee9ed2e2594e647d3d9e1d422773417800aea1",
          "sha1": "5f65fd322d8c0645d99b82cbc9ed489204a57ec4",
          "md5": "09b17d43c7cfe7b0b9e3e517c9dda36a"
        }
      ]
    }
  ]
}
