{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-repl",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "com.lihaoyi",
          "module": "ammonite_2.12.1",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1.jar",
          "url": "smack-repl-4.4.8-jitsi-1.jar",
          "size": 32696,
          "sha512": "13663bb9c6d9b335b76fe85f98830fcd4db3be398114ac56b7a5df23a33f4ba5c29fe6bccc1bdb64f9850945a1871b26e838f603f4282fa9299a1e95098ffa2e",
          "sha256": "8f763f31c6364a3ee0a376a1d8a68ddcd36dd5e1d1257a1c356659428d066a69",
          "sha1": "10df554cec8f9efcf041eb456e85f82d77cbb98d",
          "md5": "032aa0a305deb389d0fe3da950bc7f0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "com.lihaoyi",
          "module": "ammonite_2.12.1",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1.jar",
          "url": "smack-repl-4.4.8-jitsi-1.jar",
          "size": 32696,
          "sha512": "13663bb9c6d9b335b76fe85f98830fcd4db3be398114ac56b7a5df23a33f4ba5c29fe6bccc1bdb64f9850945a1871b26e838f603f4282fa9299a1e95098ffa2e",
          "sha256": "8f763f31c6364a3ee0a376a1d8a68ddcd36dd5e1d1257a1c356659428d066a69",
          "sha1": "10df554cec8f9efcf041eb456e85f82d77cbb98d",
          "md5": "032aa0a305deb389d0fe3da950bc7f0a"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-repl",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-repl-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-repl",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-repl-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
