{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-xmlparser-stax",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "a72iixft6rgjnc2ztywvkln26a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-xmlparser-stax-4.4.8-jitsi-1.jar",
          "url": "smack-xmlparser-stax-4.4.8-jitsi-1.jar",
          "size": 6707,
          "sha512": "c7cdf5547f38cdbb20b8572433cb2e1e0f32c832786cfe5810390984d0901124753e3647d08d7bdbcf09c55bfbdcb43702679546fdf3d1c078f4d6f697e34a5e",
          "sha256": "04be63183d4d5ccaa4b1c13f0e16e783fae898017e5bef6b985548348af01340",
          "sha1": "7e0d97e014d18d046808f3b1536adf6b86e44d6c",
          "md5": "e15db9ce02556fc338bef69fe08c16f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-xmlparser-stax-4.4.8-jitsi-1.jar",
          "url": "smack-xmlparser-stax-4.4.8-jitsi-1.jar",
          "size": 6707,
          "sha512": "c7cdf5547f38cdbb20b8572433cb2e1e0f32c832786cfe5810390984d0901124753e3647d08d7bdbcf09c55bfbdcb43702679546fdf3d1c078f4d6f697e34a5e",
          "sha256": "04be63183d4d5ccaa4b1c13f0e16e783fae898017e5bef6b985548348af01340",
          "sha1": "7e0d97e014d18d046808f3b1536adf6b86e44d6c",
          "md5": "e15db9ce02556fc338bef69fe08c16f0"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-stax",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-xmlparser-stax-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-xmlparser-stax-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "14b03168afba4fe3bfd92991a20317bd655f72c305aa877a5c15fb5634e834672141362a143f31bf3c7d6efb1d31df01111b851925134951cc30f750c8ab62c2",
          "sha256": "3504009935313dbb32ae36aad7a56ce45fb666c0cca1378147d10ccd6947de0f",
          "sha1": "e93942ad732a791a7dd04e087b7ca53836d80870",
          "md5": "e956ca478110f438a36a7b8a26f4f4bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-xmlparser-stax-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser-stax",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-xmlparser-stax-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-xmlparser-stax-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "14b03168afba4fe3bfd92991a20317bd655f72c305aa877a5c15fb5634e834672141362a143f31bf3c7d6efb1d31df01111b851925134951cc30f750c8ab62c2",
          "sha256": "3504009935313dbb32ae36aad7a56ce45fb666c0cca1378147d10ccd6947de0f",
          "sha1": "e93942ad732a791a7dd04e087b7ca53836d80870",
          "md5": "e956ca478110f438a36a7b8a26f4f4bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-xmlparser-stax-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
