{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-metrics-micrometer/2.0.2-jitsi/ktor-server-metrics-micrometer-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-metrics-micrometer",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.7.5"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-metrics-micrometer-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-metrics-micrometer-jvm-2.0.2-jitsi.jar",
          "size": 21594,
          "sha512": "ebdbe054985681185f71f054eaaacd48317d85aae2b8c09cdbbb6679c3c42fa3db5de7d9bb8074adf0199e1820b4c9d7096ce0c2b5749507f09405909a7707bc",
          "sha256": "ef9e94518f9fc0f895d123472cae041d92763f5ef6f199dfbf2e12b410ec05f5",
          "sha1": "3b1373aa0bba90a325aada48e9a093bd5d7724ce",
          "md5": "5b6df45fe85c855a39888d2757d54ca1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.7.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-metrics-micrometer-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-metrics-micrometer-jvm-2.0.2-jitsi.jar",
          "size": 21594,
          "sha512": "ebdbe054985681185f71f054eaaacd48317d85aae2b8c09cdbbb6679c3c42fa3db5de7d9bb8074adf0199e1820b4c9d7096ce0c2b5749507f09405909a7707bc",
          "sha256": "ef9e94518f9fc0f895d123472cae041d92763f5ef6f199dfbf2e12b410ec05f5",
          "sha1": "3b1373aa0bba90a325aada48e9a093bd5d7724ce",
          "md5": "5b6df45fe85c855a39888d2757d54ca1"
        }
      ]
    }
  ]
}
