{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-netty/2.0.2-jitsi/ktor-server-netty-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-netty",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http2",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "org.eclipse.jetty.alpn",
          "module": "alpn-api",
          "version": {
            "requires": "1.1.3.v20160715"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-netty-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-netty-jvm-2.0.2-jitsi.jar",
          "size": 203071,
          "sha512": "3db1b12458954a941abd327157f76b5dd52fd3fe09e933599aab7b043e48f4c895a7a137b627bb18bd5f759644c8c91c1ce1bb92d86e8bebd06a9846b26756c4",
          "sha256": "5d21e3a4e4c37ae309d94f04f8569a3367e5cd8a228afcec414cbffe2099beee",
          "sha1": "98b5f4e88143addf384935774eddfd977ad7388c",
          "md5": "022d7f2ce2913e914a490a62c8745ceb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http2",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "org.eclipse.jetty.alpn",
          "module": "alpn-api",
          "version": {
            "requires": "1.1.3.v20160715"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.77.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-netty-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-netty-jvm-2.0.2-jitsi.jar",
          "size": 203071,
          "sha512": "3db1b12458954a941abd327157f76b5dd52fd3fe09e933599aab7b043e48f4c895a7a137b627bb18bd5f759644c8c91c1ce1bb92d86e8bebd06a9846b26756c4",
          "sha256": "5d21e3a4e4c37ae309d94f04f8569a3367e5cd8a228afcec414cbffe2099beee",
          "sha1": "98b5f4e88143addf384935774eddfd977ad7388c",
          "md5": "022d7f2ce2913e914a490a62c8745ceb"
        }
      ]
    }
  ]
}
