{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-bosh",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.jbosh",
          "module": "jbosh",
          "version": {
            "requires": "[0.9.1,0.9.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-1.jar",
          "url": "smack-bosh-4.4.8-jitsi-1.jar",
          "size": 17879,
          "sha512": "65c1c7a50fe61e96fe05981080fb069e4f0fc92fcd4570b775b9124979a87eb2ddab330407914eedba3424478fc44a9aa1f15f09d106a6552fde62b7ee9b38e8",
          "sha256": "91c67c0cb4bf61416fc1d11a1b585fea4b61329aa76213274eb67face88401d4",
          "sha1": "c1b1ab0fc6d57cee047c7baf1eb4c90c8e36d4aa",
          "md5": "0c35f9b79f7aa40829ca694d084cb767"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.jbosh",
          "module": "jbosh",
          "version": {
            "requires": "[0.9.1,0.9.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-1.jar",
          "url": "smack-bosh-4.4.8-jitsi-1.jar",
          "size": 17879,
          "sha512": "65c1c7a50fe61e96fe05981080fb069e4f0fc92fcd4570b775b9124979a87eb2ddab330407914eedba3424478fc44a9aa1f15f09d106a6552fde62b7ee9b38e8",
          "sha256": "91c67c0cb4bf61416fc1d11a1b585fea4b61329aa76213274eb67face88401d4",
          "sha1": "c1b1ab0fc6d57cee047c7baf1eb4c90c8e36d4aa",
          "md5": "0c35f9b79f7aa40829ca694d084cb767"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-bosh-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "9183ef56968b2e3508065f4c28a82c405f3a7041eecf783dc87ee41018eeb2155c6e4ca6dee5b183c00d465e22f021deb2713892734991227604d7906d273275",
          "sha256": "d8599c49b5ba84a019a0c755d5dc548362e8733072a5aff6153599f3961f965e",
          "sha1": "f0aaceb8f97a83e46449e44b837f8ad55bf21c39",
          "md5": "edbe9616a487d7aa48567e65ee74ae05"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-bosh-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-bosh-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-bosh-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "9183ef56968b2e3508065f4c28a82c405f3a7041eecf783dc87ee41018eeb2155c6e4ca6dee5b183c00d465e22f021deb2713892734991227604d7906d273275",
          "sha256": "d8599c49b5ba84a019a0c755d5dc548362e8733072a5aff6153599f3961f965e",
          "sha1": "f0aaceb8f97a83e46449e44b837f8ad55bf21c39",
          "md5": "edbe9616a487d7aa48567e65ee74ae05"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-bosh-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
