{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-json-tests/2.0.2-jitsi/ktor-client-json-tests-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-json-tests",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-gson",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-tests",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-gson",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-tests-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-json-tests-jvm-2.0.2-jitsi.jar",
          "size": 99560,
          "sha512": "3002adae881c0abf1d633d1d78e118263d1f0fa9a8831142619e1def342769409d3b45ea4e400fea69b65bcdb8a01886530e71eb38bb79758a05ef6e8dd2ce37",
          "sha256": "3b9d0913562b0a7cd6130a8d1c611ab1a59e1caa8be58ffb76bfe8ab93c018b6",
          "sha1": "6adf415cdf3bc4d3976bf7d48834a65db2933b6e",
          "md5": "9dce11cfc34f2fbc5d87772e8ce465ec"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-gson",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-cio",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-tests",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-gson",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-json-tests-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-json-tests-jvm-2.0.2-jitsi.jar",
          "size": 99560,
          "sha512": "3002adae881c0abf1d633d1d78e118263d1f0fa9a8831142619e1def342769409d3b45ea4e400fea69b65bcdb8a01886530e71eb38bb79758a05ef6e8dd2ce37",
          "sha256": "3b9d0913562b0a7cd6130a8d1c611ab1a59e1caa8be58ffb76bfe8ab93c018b6",
          "sha1": "6adf415cdf3bc4d3976bf7d48834a65db2933b6e",
          "md5": "9dce11cfc34f2fbc5d87772e8ce465ec"
        }
      ]
    }
  ]
}
