{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-jingle-old",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "javax.media",
          "module": "jmf",
          "version": {
            "requires": "2.1.1e"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-3.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-3.jar",
          "size": 260553,
          "sha512": "624ff36a718e1690f9e19b0d116b45f239269d20dfef1a74bd402a7798efa5734b5e17c200e8145061495dc78a4e784fbc4a9cfdd02db2dcc78402eaf1cae1cf",
          "sha256": "c9693cf3180164760001a8a3067df159cb40c4f6892ccdd83c8d0ea1c679a32e",
          "sha1": "8a19655e54b984dd89cfcea8cb0a93ebe730c220",
          "md5": "eda0e074f7c05cfd2a9edaf6cf74b82e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "javax.media",
          "module": "jmf",
          "version": {
            "requires": "2.1.1e"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-3.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-3.jar",
          "size": 260553,
          "sha512": "624ff36a718e1690f9e19b0d116b45f239269d20dfef1a74bd402a7798efa5734b5e17c200e8145061495dc78a4e784fbc4a9cfdd02db2dcc78402eaf1cae1cf",
          "sha256": "c9693cf3180164760001a8a3067df159cb40c4f6892ccdd83c8d0ea1c679a32e",
          "sha1": "8a19655e54b984dd89cfcea8cb0a93ebe730c220",
          "md5": "eda0e074f7c05cfd2a9edaf6cf74b82e"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-jingle-old",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "75cc654f9affaf0f238fe638cef2978f2a8fe365a0cbc7f855cc793fbd759368f2fd28f543eefb4f7145b0f250f8d32b324e5a036043f1f245f55e06b5077e2c",
          "sha256": "e6849a74dc12656e56dc22e24f40671f71f8cb050e541a92f4e1cfc1ff86af24",
          "sha1": "d7b6a141e70d8e2d5c6359c5523c25860f034799",
          "md5": "9d1ce6467dd554d0e47b57490da0d90c"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-jingle-old-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-jingle-old",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "75cc654f9affaf0f238fe638cef2978f2a8fe365a0cbc7f855cc793fbd759368f2fd28f543eefb4f7145b0f250f8d32b324e5a036043f1f245f55e06b5077e2c",
          "sha256": "e6849a74dc12656e56dc22e24f40671f71f8cb050e541a92f4e1cfc1ff86af24",
          "sha1": "d7b6a141e70d8e2d5c6359c5523c25860f034799",
          "md5": "9d1ce6467dd554d0e47b57490da0d90c"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-jingle-old-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
