{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-xmlparser",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "a72iixft6rgjnc2ztywvkln26a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smack-xmlparser-4.4.8-jitsi-1.jar",
          "url": "smack-xmlparser-4.4.8-jitsi-1.jar",
          "size": 5981,
          "sha512": "7ae51306d0a64a39740472368e486c5c39855cbeb096cc469d64444294b2b4f4a372023c8db06c3cfc82d8a799309dcad31326aa507cb7cf36ab892eadb17004",
          "sha256": "8126b6e5878a7473c8166b90dbf35318dffc40ee772253183c8f1ed7b7c1f5d7",
          "sha1": "dc02cfacbc8b5bd7cd16a5e833faf5fc3b99acf4",
          "md5": "f04eb404fa15df961cace8d748747c05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "smack-xmlparser-4.4.8-jitsi-1.jar",
          "url": "smack-xmlparser-4.4.8-jitsi-1.jar",
          "size": 5981,
          "sha512": "7ae51306d0a64a39740472368e486c5c39855cbeb096cc469d64444294b2b4f4a372023c8db06c3cfc82d8a799309dcad31326aa507cb7cf36ab892eadb17004",
          "sha256": "8126b6e5878a7473c8166b90dbf35318dffc40ee772253183c8f1ed7b7c1f5d7",
          "sha1": "dc02cfacbc8b5bd7cd16a5e833faf5fc3b99acf4",
          "md5": "f04eb404fa15df961cace8d748747c05"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-xmlparser-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-xmlparser-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "14b03168afba4fe3bfd92991a20317bd655f72c305aa877a5c15fb5634e834672141362a143f31bf3c7d6efb1d31df01111b851925134951cc30f750c8ab62c2",
          "sha256": "3504009935313dbb32ae36aad7a56ce45fb666c0cca1378147d10ccd6947de0f",
          "sha1": "e93942ad732a791a7dd04e087b7ca53836d80870",
          "md5": "e956ca478110f438a36a7b8a26f4f4bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-xmlparser-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-xmlparser",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-xmlparser-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-xmlparser-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "14b03168afba4fe3bfd92991a20317bd655f72c305aa877a5c15fb5634e834672141362a143f31bf3c7d6efb1d31df01111b851925134951cc30f750c8ab62c2",
          "sha256": "3504009935313dbb32ae36aad7a56ce45fb666c0cca1378147d10ccd6947de0f",
          "sha1": "e93942ad732a791a7dd04e087b7ca53836d80870",
          "md5": "e956ca478110f438a36a7b8a26f4f4bc"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-xmlparser-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
