{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-sasl-provided",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-3.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-3.jar",
          "size": 10714,
          "sha512": "ead7c5b2a1391c3e0d2f8edeadc9e4f8f3cd27fad80d1348d36c6ffb9ee8bc211c79e562f857cc64b0573eae64fb1a7720c1366ff9fcdbf71ddbbcddd1dc0eea",
          "sha256": "dbbf6c372239a48b8f53b69faff9bb0afaddf88663e69da262d81c8d45b69cde",
          "sha1": "2c75d410a7e4965964289110ab4e03867af4085e",
          "md5": "806141bb4f3fdf6ed2b0aa2be5f2e90b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-3.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-3.jar",
          "size": 10714,
          "sha512": "ead7c5b2a1391c3e0d2f8edeadc9e4f8f3cd27fad80d1348d36c6ffb9ee8bc211c79e562f857cc64b0573eae64fb1a7720c1366ff9fcdbf71ddbbcddd1dc0eea",
          "sha256": "dbbf6c372239a48b8f53b69faff9bb0afaddf88663e69da262d81c8d45b69cde",
          "sha1": "2c75d410a7e4965964289110ab4e03867af4085e",
          "md5": "806141bb4f3fdf6ed2b0aa2be5f2e90b"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-sasl-provided",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "146379d13d316e7d44373f705ddf31e9cf8c6961364fd193682cd44f21a88e45983b8df70048625cbf38fbd0cddf304ec9d65b83a715897fdef42fe18be58c26",
          "sha256": "60413c662cd2cff3c0efd4d99b318d2bee704c6e3202a0397f731658f2eeacfd",
          "sha1": "0a24531472e36a44371732b0bbfb8510d2948727",
          "md5": "75a03c2072d75d447d5a4e93bd4a981e"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-sasl-provided-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-sasl-provided",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-sasl-provided-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-sasl-provided-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "146379d13d316e7d44373f705ddf31e9cf8c6961364fd193682cd44f21a88e45983b8df70048625cbf38fbd0cddf304ec9d65b83a715897fdef42fe18be58c26",
          "sha256": "60413c662cd2cff3c0efd4d99b318d2bee704c6e3202a0397f731658f2eeacfd",
          "sha1": "0a24531472e36a44371732b0bbfb8510d2948727",
          "md5": "75a03c2072d75d447d5a4e93bd4a981e"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-sasl-provided-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
