{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auth-ldap/2.0.2-jitsi/ktor-server-auth-ldap-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-auth-ldap",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auth-ldap-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-auth-ldap-jvm-2.0.2-jitsi.jar",
          "size": 8554,
          "sha512": "028c40e46952396b883007efd2f7722ee9225039463c44433fec47bf7c4b9243d210dadb01717fbd35c92f1e84fe694cb1fac91c3ba756a19d53d6a8f3650781",
          "sha256": "f3cedb9ce34dc0eed3a668064fbfde8b1caa2e04b24a409986ad778c3fb25498",
          "sha1": "4ed953279953f229ae00b7a652b601fcb9cfe54a",
          "md5": "4a0c3d44e33ee1684736840e13d6b7d7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auth-ldap-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-auth-ldap-jvm-2.0.2-jitsi.jar",
          "size": 8554,
          "sha512": "028c40e46952396b883007efd2f7722ee9225039463c44433fec47bf7c4b9243d210dadb01717fbd35c92f1e84fe694cb1fac91c3ba756a19d53d6a8f3650781",
          "sha256": "f3cedb9ce34dc0eed3a668064fbfde8b1caa2e04b24a409986ad778c3fb25498",
          "sha1": "4ed953279953f229ae00b7a652b601fcb9cfe54a",
          "md5": "4a0c3d44e33ee1684736840e13d6b7d7"
        }
      ]
    }
  ]
}
