{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-locations/2.0.2-jitsi/ktor-server-locations-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-locations",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-data-conversion",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-locations-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-locations-jvm-2.0.2-jitsi.jar",
          "size": 64046,
          "sha512": "966e2b0cd567d2471dd72e3dd53fb22b24bf0e5132c02fd758af3282325557ebd47f0190edbc711d5cbee6acc49175f30f8d9ece8929740c36d353b7b7b5ff64",
          "sha256": "7a795098a3a0d64352caac3196ac400290ba6a70970250f72a9cc91f6ba9ed9f",
          "sha1": "c8fb6b2c77c43babbf218490a50959cbcf852b3f",
          "md5": "f6c43bf5fbafe2e587b7702b0b142fff"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-data-conversion",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-locations-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-locations-jvm-2.0.2-jitsi.jar",
          "size": 64046,
          "sha512": "966e2b0cd567d2471dd72e3dd53fb22b24bf0e5132c02fd758af3282325557ebd47f0190edbc711d5cbee6acc49175f30f8d9ece8929740c36d353b7b7b5ff64",
          "sha256": "7a795098a3a0d64352caac3196ac400290ba6a70970250f72a9cc91f6ba9ed9f",
          "sha1": "c8fb6b2c77c43babbf218490a50959cbcf852b3f",
          "md5": "f6c43bf5fbafe2e587b7702b0b142fff"
        }
      ]
    }
  ]
}
