{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-java8-full",
    "version": "4.4.8-jitsi-4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "55gr4pkpovd5dd4fmxotu6cy3u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-4.jar",
          "url": "smack-java8-full-4.4.8-jitsi-4.jar",
          "size": 2645,
          "sha512": "8acd9638f2df85e49acf3d64882543dc88a4e43e0f52e9b85c8ee0335b0f19d3ef32190e400cc9655c1f280f19ea1f678a741c64b22d2c423cc2a88bee50b072",
          "sha256": "bad145166bdf620f93a44bf030805b3fa72b5173889581ecb2523c4d3ede55de",
          "sha1": "a9ef7a0b474699f2252d1cb5f8c92f1876b34207",
          "md5": "d88c72ac562b92c10e67202b2bf6bda4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-4.jar",
          "url": "smack-java8-full-4.4.8-jitsi-4.jar",
          "size": 2645,
          "sha512": "8acd9638f2df85e49acf3d64882543dc88a4e43e0f52e9b85c8ee0335b0f19d3ef32190e400cc9655c1f280f19ea1f678a741c64b22d2c423cc2a88bee50b072",
          "sha256": "bad145166bdf620f93a44bf030805b3fa72b5173889581ecb2523c4d3ede55de",
          "sha1": "a9ef7a0b474699f2252d1cb5f8c92f1876b34207",
          "md5": "d88c72ac562b92c10e67202b2bf6bda4"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-4-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-4-test-fixtures.jar",
          "size": 261,
          "sha512": "708db29f3562ce739743562b8066993802902c17017cf4d573ec202dc8dc326f4653f12b907eab9f22152f93854055a13837d20942fc638ba7a3f87b98003124",
          "sha256": "a088d42dcbcc233be582b5ced3888fefd38e2efb8e469c2d7fb798fab433ad38",
          "sha1": "2838c6d06ea3e31814b5196ba299402dc909d6a9",
          "md5": "95027c4a4a1b1be68e76cd32307d7813"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-4"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-4"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-4-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-4-test-fixtures.jar",
          "size": 261,
          "sha512": "708db29f3562ce739743562b8066993802902c17017cf4d573ec202dc8dc326f4653f12b907eab9f22152f93854055a13837d20942fc638ba7a3f87b98003124",
          "sha256": "a088d42dcbcc233be582b5ced3888fefd38e2efb8e469c2d7fb798fab433ad38",
          "sha1": "2838c6d06ea3e31814b5196ba299402dc909d6a9",
          "md5": "95027c4a4a1b1be68e76cd32307d7813"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-4"
        }
      ]
    }
  ]
}
