{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-repl",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xocdu4aluvh3hiulg7bwc7qemy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "com.lihaoyi",
          "module": "ammonite_2.12.1",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1.jar",
          "url": "smack-repl-4.4.8-jitsi-1.jar",
          "size": 32694,
          "sha512": "99b8ae4c664106f536c78b445f93c61ea8bc6b9b2ad583bca0d7b383d9a85a2a0c7cddf44acede8f0cab17cf90e8af104efd8cffbeb9f937e06005d22900236d",
          "sha256": "d648f3b1432bb0d09e684757f6bc5074e56e9616e6618e5a4148d782c1dc1452",
          "sha1": "c3ac943c598d072a15b1be5a212cb0a150259273",
          "md5": "bc7eb9d1bad5bfb5a6a859ed2657d89a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala-library",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "com.lihaoyi",
          "module": "ammonite_2.12.1",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo-signal",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1.jar",
          "url": "smack-repl-4.4.8-jitsi-1.jar",
          "size": 32694,
          "sha512": "99b8ae4c664106f536c78b445f93c61ea8bc6b9b2ad583bca0d7b383d9a85a2a0c7cddf44acede8f0cab17cf90e8af104efd8cffbeb9f937e06005d22900236d",
          "sha256": "d648f3b1432bb0d09e684757f6bc5074e56e9616e6618e5a4148d782c1dc1452",
          "sha1": "c3ac943c598d072a15b1be5a212cb0a150259273",
          "md5": "bc7eb9d1bad5bfb5a6a859ed2657d89a"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-repl",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-repl-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-repl",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-repl-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-repl-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
