{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-debug-slf4j",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7,1.8)"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-1.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-1.jar",
          "size": 7034,
          "sha512": "21428befff153d1f7252540cf0c799b7030f76ade0442a29ae0fa18913e7bd3121bb95560e5829d8bd069f4403d74ec1fc9f03ffa0291d501455e5b28196b3d1",
          "sha256": "a78078dd688e11fdb8ba41baed6d3a109df2ea802013e3ba555d74e3dcd47219",
          "sha1": "29c9d0c167cd2720f0be3dc138370778b932779f",
          "md5": "b3a409223b7bb5d77c6e04dccba68205"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7,1.8)"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-1.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-1.jar",
          "size": 7034,
          "sha512": "21428befff153d1f7252540cf0c799b7030f76ade0442a29ae0fa18913e7bd3121bb95560e5829d8bd069f4403d74ec1fc9f03ffa0291d501455e5b28196b3d1",
          "sha256": "a78078dd688e11fdb8ba41baed6d3a109df2ea802013e3ba555d74e3dcd47219",
          "sha1": "29c9d0c167cd2720f0be3dc138370778b932779f",
          "md5": "b3a409223b7bb5d77c6e04dccba68205"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug-slf4j",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "a6863ec3609183158253fe7c129fed0ee0f4abb0087d0586d73a868609c80a6643b688036df6b46b5bea8ea53895669eee319d99a079a3435dc54012f658446b",
          "sha256": "4e36d045bf014215c1da32b57f8c745c00129c34cc5b411eeb0e75bdca976007",
          "sha1": "d9ed062eb7a7dcd07d7152f7d1525be09e031989",
          "md5": "7f32147f83b342d8ead49c08e646806f"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-debug-slf4j-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug-slf4j",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "a6863ec3609183158253fe7c129fed0ee0f4abb0087d0586d73a868609c80a6643b688036df6b46b5bea8ea53895669eee319d99a079a3435dc54012f658446b",
          "sha256": "4e36d045bf014215c1da32b57f8c745c00129c34cc5b411eeb0e75bdca976007",
          "sha1": "d9ed062eb7a7dcd07d7152f7d1525be09e031989",
          "md5": "7f32147f83b342d8ead49c08e646806f"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-debug-slf4j-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
