{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-jingle-old",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xocdu4aluvh3hiulg7bwc7qemy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "javax.media",
          "module": "jmf",
          "version": {
            "requires": "2.1.1e"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "size": 260551,
          "sha512": "b8fafe1e6104992098143e7c316f503ac36871d70e09ce044c7a6832cba20a261827509d2dd3155a4813fdb66d5220e839f74578961d1d0938be49a97fa7917c",
          "sha256": "7f4fb2db76e8981e7f44c1cbadef54a5b81ce042660c566f5257453ddb429789",
          "sha1": "0ae84d1723440ae86850d643afb11162e6ada901",
          "md5": "acde65ff0ffe4ddd65889d9d2a74526e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "javax.media",
          "module": "jmf",
          "version": {
            "requires": "2.1.1e"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1.jar",
          "size": 260551,
          "sha512": "b8fafe1e6104992098143e7c316f503ac36871d70e09ce044c7a6832cba20a261827509d2dd3155a4813fdb66d5220e839f74578961d1d0938be49a97fa7917c",
          "sha256": "7f4fb2db76e8981e7f44c1cbadef54a5b81ce042660c566f5257453ddb429789",
          "sha1": "0ae84d1723440ae86850d643afb11162e6ada901",
          "md5": "acde65ff0ffe4ddd65889d9d2a74526e"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-jingle-old",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "d224a10ba260492d420e249ae3db11ae047d369f8fd7a2d76229c7e8869d653462b9dcb8a20200509a7108615206cf3dcb7afb421e928e67e9ecedc9a02e91ee",
          "sha256": "8916274574c3f89a6d34b5201a05a06e93ba306aae600cf68111557e6eedba75",
          "sha1": "874a9b9ae58d985b7a3ac35b4d7a470896dec571",
          "md5": "91a1178f4e4599cd79d7fbfe305fe468"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-jingle-old-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-jingle-old",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-jingle-old-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "d224a10ba260492d420e249ae3db11ae047d369f8fd7a2d76229c7e8869d653462b9dcb8a20200509a7108615206cf3dcb7afb421e928e67e9ecedc9a02e91ee",
          "sha256": "8916274574c3f89a6d34b5201a05a06e93ba306aae600cf68111557e6eedba75",
          "sha1": "874a9b9ae58d985b7a3ac35b4d7a470896dec571",
          "md5": "91a1178f4e4599cd79d7fbfe305fe468"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-jingle-old-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
