{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-shared/2.0.2-jitsi/ktor-shared-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-shared",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-shared-jvm-2.0.2-jitsi.jar",
          "url": "ktor-shared-jvm-2.0.2-jitsi.jar",
          "size": 341,
          "sha512": "538eeee03ad11c8533340412a10cf2e48edb45e25a2c215b7de2d2fe3b2301bacf8d3a995d8180db6836811bd260dd94d500b9ab198782b7198ad82b99223721",
          "sha256": "46cb7ed3785a936cf05d53fc83a310a677493a6d175250b94b3b9a229b64a903",
          "sha1": "30186d39c39ae23f194846c36aa0711e678879cd",
          "md5": "49e661bf278f08c86317ee257aa4655b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-shared-jvm-2.0.2-jitsi.jar",
          "url": "ktor-shared-jvm-2.0.2-jitsi.jar",
          "size": 341,
          "sha512": "538eeee03ad11c8533340412a10cf2e48edb45e25a2c215b7de2d2fe3b2301bacf8d3a995d8180db6836811bd260dd94d500b9ab198782b7198ad82b99223721",
          "sha256": "46cb7ed3785a936cf05d53fc83a310a677493a6d175250b94b3b9a229b64a903",
          "sha1": "30186d39c39ae23f194846c36aa0711e678879cd",
          "md5": "49e661bf278f08c86317ee257aa4655b"
        }
      ]
    }
  ]
}
