{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-experimental",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.hsluv",
          "module": "hsluv",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "smack-experimental-4.4.8-jitsi-3.jar",
          "url": "smack-experimental-4.4.8-jitsi-3.jar",
          "size": 451195,
          "sha512": "8d73968049e53b613b1aa55ba4bb1a74689db8ff1fc65a9860d3cec485c27569f64913d93b03b44df5ac64fb886e9a59d3d53eb198069c5c0c4eb1d55e08bf4c",
          "sha256": "729e0dcbc56fc09057370ab5666ee4db37051a24e767e425f820bd36986c99c5",
          "sha1": "b3d1380386f23828e6f259a3900ae917f53b34ad",
          "md5": "c9227bdffdf538ca72fdb823bed98cfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.hsluv",
          "module": "hsluv",
          "version": {
            "requires": "0.2"
          }
        }
      ],
      "files": [
        {
          "name": "smack-experimental-4.4.8-jitsi-3.jar",
          "url": "smack-experimental-4.4.8-jitsi-3.jar",
          "size": 451195,
          "sha512": "8d73968049e53b613b1aa55ba4bb1a74689db8ff1fc65a9860d3cec485c27569f64913d93b03b44df5ac64fb886e9a59d3d53eb198069c5c0c4eb1d55e08bf4c",
          "sha256": "729e0dcbc56fc09057370ab5666ee4db37051a24e767e425f820bd36986c99c5",
          "sha1": "b3d1380386f23828e6f259a3900ae917f53b34ad",
          "md5": "c9227bdffdf538ca72fdb823bed98cfb"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-extensions-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-experimental-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-experimental-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "8fb8406b7a30d4a86646610d7ea8ff9693769aa0469aa0973ac471f3d304f2c63145e83bd59c916cbdbff9245e5dfee7c3dfa390550678bbd87035f5cc24be59",
          "sha256": "146e663b18a7c99d79ad8cb6253ba12ed940e6d0500ef66b760c6a2ad152b1af",
          "sha1": "347e78f02642b73bca61ea2b7dc0658e47d6526b",
          "md5": "6e1eb7803a7e7e3d155510144986efbb"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-experimental-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-3"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-extensions-test-fixtures",
              "version": "4.4.8-jitsi-3"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-experimental-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-experimental-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "8fb8406b7a30d4a86646610d7ea8ff9693769aa0469aa0973ac471f3d304f2c63145e83bd59c916cbdbff9245e5dfee7c3dfa390550678bbd87035f5cc24be59",
          "sha256": "146e663b18a7c99d79ad8cb6253ba12ed940e6d0500ef66b760c6a2ad152b1af",
          "sha1": "347e78f02642b73bca61ea2b7dc0658e47d6526b",
          "md5": "6e1eb7803a7e7e3d155510144986efbb"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-experimental-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
