{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-javax",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-3.jar",
          "size": 4275,
          "sha512": "1ec42ea86c5dde4aa985ad14309451de2f1e6e63bf9ce5a8ec3eb2ce41f9b874eb43fc3053a29b7e823c0f133c33608dfb2df57a5e06678f846c6fef564f89a4",
          "sha256": "21704ce9c821c9596d7eaf2302750bf9cfb7b68cb08118c075bd74530facd037",
          "sha1": "fd198bd8fb8873d7a680f6beb2910d4e88f1375a",
          "md5": "bd88987f989f49409230e1cb9678dd58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-3.jar",
          "size": 4275,
          "sha512": "1ec42ea86c5dde4aa985ad14309451de2f1e6e63bf9ce5a8ec3eb2ce41f9b874eb43fc3053a29b7e823c0f133c33608dfb2df57a5e06678f846c6fef564f89a4",
          "sha256": "21704ce9c821c9596d7eaf2302750bf9cfb7b68cb08118c075bd74530facd037",
          "sha1": "fd198bd8fb8873d7a680f6beb2910d4e88f1375a",
          "md5": "bd88987f989f49409230e1cb9678dd58"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-javax",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "a108bbad98d32839bca2df9ebb8e709eb8c8bddaaf2ea86cd4acc61275bf2a7c9108cb2c84cf69e04295c3333d5cfdb597431a6d2a1a5d5a3aaa018a087f46dc",
          "sha256": "abb80c93547d47f9ddebf1b42484e63596f21a08349bc8c304e3657e40bc4187",
          "sha1": "203e60f08bbeb55633f724e7dd534a3a9b5b9a73",
          "md5": "3fb23e27c9c42f37c409f071f9dd370a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-javax-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-javax",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-javax-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-javax-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "a108bbad98d32839bca2df9ebb8e709eb8c8bddaaf2ea86cd4acc61275bf2a7c9108cb2c84cf69e04295c3333d5cfdb597431a6d2a1a5d5a3aaa018a087f46dc",
          "sha256": "abb80c93547d47f9ddebf1b42484e63596f21a08349bc8c304e3657e40bc4187",
          "sha1": "203e60f08bbeb55633f724e7dd534a3a9b5b9a73",
          "md5": "3fb23e27c9c42f37c409f071f9dd370a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-javax-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
