{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-xml/2.0.2-jitsi/ktor-serialization-kotlinx-xml-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-serialization-kotlinx-xml",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.84.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-jvm-2.0.2-jitsi.jar",
          "url": "ktor-serialization-kotlinx-xml-jvm-2.0.2-jitsi.jar",
          "size": 3771,
          "sha512": "5da1497554a0d03c632713a6de3a18b45f5cf1be6cb293a07d53d5e5e96cf4c4093d3f52fa6b44546656158b70b258bf4c4c150c6720ca5d4f39e4a1fc5a84e9",
          "sha256": "0023850da8e5a9bf78e3da4c5f8df1b2735c75043902eebc3a34a913aa79070f",
          "sha1": "009e0533fc416ebd583406eb66dab8b8c66edf2f",
          "md5": "8ccbb412bed9b67a8c3a89090d6a4a1b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.github.pdvrieze.xmlutil",
          "module": "serialization",
          "version": {
            "requires": "0.84.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-xml-jvm-2.0.2-jitsi.jar",
          "url": "ktor-serialization-kotlinx-xml-jvm-2.0.2-jitsi.jar",
          "size": 3771,
          "sha512": "5da1497554a0d03c632713a6de3a18b45f5cf1be6cb293a07d53d5e5e96cf4c4093d3f52fa6b44546656158b70b258bf4c4c150c6720ca5d4f39e4a1fc5a84e9",
          "sha256": "0023850da8e5a9bf78e3da4c5f8df1b2735c75043902eebc3a34a913aa79070f",
          "sha1": "009e0533fc416ebd583406eb66dab8b8c66edf2f",
          "md5": "8ccbb412bed9b67a8c3a89090d6a4a1b"
        }
      ]
    }
  ]
}
