{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-integration-test",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "eu.geekplace.javapinning",
          "module": "java-pinning-java7",
          "version": {
            "requires": "1.1.0-alpha1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-dnsjava",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-integration-test-4.4.8-jitsi-1.jar",
          "url": "smack-integration-test-4.4.8-jitsi-1.jar",
          "size": 207521,
          "sha512": "6d27a240e614bb1bceb3261a8460b157ce4ebd9989a3af3730451ab8a7ba6598638015a914717495f6c650b09e13abed15d1eba6d0cba7f8e9d28813574db4f0",
          "sha256": "32ad4b590bbba29d0e3715501fbd49057aa61ac719e4ada0c080a0ccbac40ad1",
          "sha1": "658c2d7ffa9069ecdcfe7d49414d82cf40bc8551",
          "md5": "d9fa6ab538a378fcd133d7fceb451281"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "eu.geekplace.javapinning",
          "module": "java-pinning-java7",
          "version": {
            "requires": "1.1.0-alpha1"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-dnsjava",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-integration-test-4.4.8-jitsi-1.jar",
          "url": "smack-integration-test-4.4.8-jitsi-1.jar",
          "size": 207521,
          "sha512": "6d27a240e614bb1bceb3261a8460b157ce4ebd9989a3af3730451ab8a7ba6598638015a914717495f6c650b09e13abed15d1eba6d0cba7f8e9d28813574db4f0",
          "sha256": "32ad4b590bbba29d0e3715501fbd49057aa61ac719e4ada0c080a0ccbac40ad1",
          "sha1": "658c2d7ffa9069ecdcfe7d49414d82cf40bc8551",
          "md5": "d9fa6ab538a378fcd133d7fceb451281"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "af37076f2823b3e96871679a653ba16e8c1aa47038beaf77effede10a04fb71d15cbf2272820b62be95a3a0474c3dd24415c3c1b4f47637c90103e28e4728924",
          "sha256": "d7a68150343f67bed2c9febdc909616220ac6a9aee8800735ec164572fc85db2",
          "sha1": "c7223eec0d82eaeb34333bf509d0b8ef040a4701",
          "md5": "ae95b94eba92580db1fbfac499e487e5"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-integration-test-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-integration-test",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          },
          "requestedCapabilities": [
            {
              "group": "org.igniterealtime.smack",
              "name": "smack-core-test-fixtures",
              "version": "4.4.8-jitsi-1"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "smack-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-integration-test-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "af37076f2823b3e96871679a653ba16e8c1aa47038beaf77effede10a04fb71d15cbf2272820b62be95a3a0474c3dd24415c3c1b4f47637c90103e28e4728924",
          "sha256": "d7a68150343f67bed2c9febdc909616220ac6a9aee8800735ec164572fc85db2",
          "sha1": "c7223eec0d82eaeb34333bf509d0b8ef040a4701",
          "md5": "ae95b94eba92580db1fbfac499e487e5"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-integration-test-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
