{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-compression/2.0.2-jitsi/ktor-server-compression-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-compression",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-compression-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-compression-jvm-2.0.2-jitsi.jar",
          "size": 62418,
          "sha512": "791e81a002d3a40b170669f61742cba967966e888d66723746ee37742498551def12a8836ac6ce6d708310f2c4b574d43042379db516f1248fa91bc44cad2341",
          "sha256": "248f959623d6c68a30d5f3c6a0db22edc32de34f03b654a2e38abee6900a5665",
          "sha1": "f9f1e6a1caf9dab1a8aa89c32526fa6d390f7f4f",
          "md5": "8be641c9f43faf4e79228b065760a447"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-compression-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-compression-jvm-2.0.2-jitsi.jar",
          "size": 62418,
          "sha512": "791e81a002d3a40b170669f61742cba967966e888d66723746ee37742498551def12a8836ac6ce6d708310f2c4b574d43042379db516f1248fa91bc44cad2341",
          "sha256": "248f959623d6c68a30d5f3c6a0db22edc32de34f03b654a2e38abee6900a5665",
          "sha1": "f9f1e6a1caf9dab1a8aa89c32526fa6d390f7f4f",
          "md5": "8be641c9f43faf4e79228b065760a447"
        }
      ]
    }
  ]
}
