{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-apache/2.0.2-jitsi/ktor-client-apache-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-apache",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpasyncclient",
          "version": {
            "requires": "4.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-apache-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-apache-jvm-2.0.2-jitsi.jar",
          "size": 52661,
          "sha512": "b1a810c11e2850264c258a365a8307d532a19884c4fa89e5fa92e850f38ce5d24650b24ddcd1d36b068bb5bcb76c1623a65f358ff51937fde989e10a2a5ad881",
          "sha256": "8891714c37887a6871d145e9a5e53cf3f9b62c059f531880b53fdd4ef45a1b64",
          "sha1": "981cbcb5f87fa0c3017a165eba94acd2752f13a0",
          "md5": "7ab6c65423431b996f25d8d19fb2d8e7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpasyncclient",
          "version": {
            "requires": "4.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-apache-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-apache-jvm-2.0.2-jitsi.jar",
          "size": 52661,
          "sha512": "b1a810c11e2850264c258a365a8307d532a19884c4fa89e5fa92e850f38ce5d24650b24ddcd1d36b068bb5bcb76c1623a65f358ff51937fde989e10a2a5ad881",
          "sha256": "8891714c37887a6871d145e9a5e53cf3f9b62c059f531880b53fdd4ef45a1b64",
          "sha1": "981cbcb5f87fa0c3017a165eba94acd2752f13a0",
          "md5": "7ab6c65423431b996f25d8d19fb2d8e7"
        }
      ]
    }
  ]
}
