{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-servlet5/2.0.2-jitsi/ktor-server-servlet5-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-servlet5",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-servlet5-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-servlet5-jvm-2.0.2-jitsi.jar",
          "size": 123053,
          "sha512": "bcae1cc6cb00ba446d00c1b15ac32043fe793317f85842926eb093ade7176f44efeb5ad3620c2b665c5ff8f90b840236822b39f1add2cc6d644b9f082ab9b415",
          "sha256": "cbe72277652f85e8bce614dafe516c35b91cc72ab6105768c6240961458540cc",
          "sha1": "eb42cb43188868753124486cd6b4052f44119e34",
          "md5": "a76669eaccfa4d76b53e35656279dfcc"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-servlet5-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-servlet5-jvm-2.0.2-jitsi.jar",
          "size": 123053,
          "sha512": "bcae1cc6cb00ba446d00c1b15ac32043fe793317f85842926eb093ade7176f44efeb5ad3620c2b665c5ff8f90b840236822b39f1add2cc6d644b9f082ab9b415",
          "sha256": "cbe72277652f85e8bce614dafe516c35b91cc72ab6105768c6240961458540cc",
          "sha1": "eb42cb43188868753124486cd6b4052f44119e34",
          "md5": "a76669eaccfa4d76b53e35656279dfcc"
        }
      ]
    }
  ]
}
