{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-debug-slf4j",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7,1.8)"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-3.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-3.jar",
          "size": 7033,
          "sha512": "223bfa84fccf8cbb78205a9448dfb6b031c55871aa60b3e3854bbf3b0bca65ff5fb9d9aecb3c87c54be2b4845573c8e7f059d6971364378937c7dacc2543724f",
          "sha256": "aa3fd6e7977868a79984eece02d269d3640d83051c29f6aeef4dadd436099fc8",
          "sha1": "d7c3fee28718cee5ca675a5cc7384cb16dac8d1c",
          "md5": "1c1bbda8f15f26d21719241d9a92bb27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "[1.7,1.8)"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-3.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-3.jar",
          "size": 7033,
          "sha512": "223bfa84fccf8cbb78205a9448dfb6b031c55871aa60b3e3854bbf3b0bca65ff5fb9d9aecb3c87c54be2b4845573c8e7f059d6971364378937c7dacc2543724f",
          "sha256": "aa3fd6e7977868a79984eece02d269d3640d83051c29f6aeef4dadd436099fc8",
          "sha1": "d7c3fee28718cee5ca675a5cc7384cb16dac8d1c",
          "md5": "1c1bbda8f15f26d21719241d9a92bb27"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug-slf4j",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "9196035b904f0bc5beaaa5182fc42db378ef7e7cc90c7dad3baecfc82ad90e1793f7bcedb099b1862d45f4cc65cb964400fdc86c7313487bc254ce4e0fef50dc",
          "sha256": "965b898d0ca6a102705996aae226c6dab2d6d8536d49a3b09c64850b3b2889a9",
          "sha1": "983b9e024c30a3355c0197e2310e2b34695f6132",
          "md5": "eb8b2f017eee0e23cd2e31395a02fa8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-debug-slf4j-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug-slf4j",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-slf4j-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-debug-slf4j-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "9196035b904f0bc5beaaa5182fc42db378ef7e7cc90c7dad3baecfc82ad90e1793f7bcedb099b1862d45f4cc65cb964400fdc86c7313487bc254ce4e0fef50dc",
          "sha256": "965b898d0ca6a102705996aae226c6dab2d6d8536d49a3b09c64850b3b2889a9",
          "sha1": "983b9e024c30a3355c0197e2310e2b34695f6132",
          "md5": "eb8b2f017eee0e23cd2e31395a02fa8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-debug-slf4j-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
