{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor/2.0.2-jitsi/ktor-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-2.0.2-jitsi.jar",
          "url": "ktor-jvm-2.0.2-jitsi.jar",
          "size": 336,
          "sha512": "481853880a76a61de52f411f5a92152945ed3311372ad30cd491a243a1a7deb4de759b60d4fcda406a4885ba92133e9b06b6013ac902355f6a9a7112251c9588",
          "sha256": "cf46996d15569c8e613b8a6c0e414a3dd2ef3df25375008c887acf7f886421e2",
          "sha1": "02b38174da3658403ade0343906b56ecb72f57d3",
          "md5": "2aff6713cef5287ddaea87a468f9aeb6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-jvm-2.0.2-jitsi.jar",
          "url": "ktor-jvm-2.0.2-jitsi.jar",
          "size": 336,
          "sha512": "481853880a76a61de52f411f5a92152945ed3311372ad30cd491a243a1a7deb4de759b60d4fcda406a4885ba92133e9b06b6013ac902355f6a9a7112251c9588",
          "sha256": "cf46996d15569c8e613b8a6c0e414a3dd2ef3df25375008c887acf7f886421e2",
          "sha1": "02b38174da3658403ade0343906b56ecb72f57d3",
          "md5": "2aff6713cef5287ddaea87a468f9aeb6"
        }
      ]
    }
  ]
}
