{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-debug",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xocdu4aluvh3hiulg7bwc7qemy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-4.4.8-jitsi-1.jar",
          "url": "smack-debug-4.4.8-jitsi-1.jar",
          "size": 68599,
          "sha512": "37dcfc7f7d9041003b5dd60161ba21c12abd49cde368cebb28ae402415e50a7ac89dc6c69800754c5d2b21b67d83d439f0c6cb45d720e226280090792c1d5d81",
          "sha256": "34adab315f2d4f6ddac937cfbdcce1b436f9c22453d65f271a6ba26e194247d2",
          "sha1": "1ded8c94d647b13d651e3661881ed44382ded55f",
          "md5": "01ec17812c225e4f4cf537df80c238a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-4.4.8-jitsi-1.jar",
          "url": "smack-debug-4.4.8-jitsi-1.jar",
          "size": 68599,
          "sha512": "37dcfc7f7d9041003b5dd60161ba21c12abd49cde368cebb28ae402415e50a7ac89dc6c69800754c5d2b21b67d83d439f0c6cb45d720e226280090792c1d5d81",
          "sha256": "34adab315f2d4f6ddac937cfbdcce1b436f9c22453d65f271a6ba26e194247d2",
          "sha1": "1ded8c94d647b13d651e3661881ed44382ded55f",
          "md5": "01ec17812c225e4f4cf537df80c238a4"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-debug-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "b27927b35979b30caadcf777eba12c6f56139d21f8b2300e6bb6a980748d8fec34a8fd4cc7d35d3d7306f03511788205b91855787fd2b582488def86af8b29a0",
          "sha256": "c8313d003c8041563a9d73bbd15992b1d9d142e8b2c9ce34d57001d94af86db7",
          "sha1": "4700cc2d58d7858adc1b0f28bc1f28c8bc5ed15b",
          "md5": "54f7e1b1d8f3839481a1aabfc6fc8298"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-debug-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-debug-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-debug-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "b27927b35979b30caadcf777eba12c6f56139d21f8b2300e6bb6a980748d8fec34a8fd4cc7d35d3d7306f03511788205b91855787fd2b582488def86af8b29a0",
          "sha256": "c8313d003c8041563a9d73bbd15992b1d9d142e8b2c9ce34d57001d94af86db7",
          "sha1": "4700cc2d58d7858adc1b0f28bc1f28c8bc5ed15b",
          "md5": "54f7e1b1d8f3839481a1aabfc6fc8298"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-debug-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
