{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-tests/2.0.2-jitsi/ktor-client-tests-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client-tests",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls-certificates",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-jetty",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-websockets",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-test-dispatcher",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-tests-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-tests-jvm-2.0.2-jitsi.jar",
          "size": 557709,
          "sha512": "156a6a7e7fe5a1aedf1af24e412677188ceea87deabfa431c5bad35dc8d0e0cce50f83572b8a75a67794c6d82f7cabfe0d3ee37a5610e09c1844b9f6e92b8872",
          "sha256": "6a8b3608d56df6f25dc54a28fd74924caf0f4e45ee64dc5f36fc95dbf8796f1d",
          "sha1": "908602580e69ad373bcff3cb83ddbe5ed7cf0ea2",
          "md5": "1360670a0e69cde062edee77844fa39f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls-certificates",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-cio",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-jetty",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-websockets",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.11"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-test-dispatcher",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-tests-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-tests-jvm-2.0.2-jitsi.jar",
          "size": 557709,
          "sha512": "156a6a7e7fe5a1aedf1af24e412677188ceea87deabfa431c5bad35dc8d0e0cce50f83572b8a75a67794c6d82f7cabfe0d3ee37a5610e09c1844b9f6e92b8872",
          "sha256": "6a8b3608d56df6f25dc54a28fd74924caf0f4e45ee64dc5f36fc95dbf8796f1d",
          "sha1": "908602580e69ad373bcff3cb83ddbe5ed7cf0ea2",
          "md5": "1360670a0e69cde062edee77844fa39f"
        }
      ]
    }
  ]
}
