{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-android-extensions",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-1.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-1.jar",
          "size": 6253,
          "sha512": "95dcdd66bae11a1b2da12eceb76db65e9e398376bcfe91c053f1cbede27d9828a37ccd3e562ab63a48acdb27c194674de81d103605380794d576b363beaabd06",
          "sha256": "257a8ba1a7059fc35e7b4e7c41ba0b3ce9c918a46e07d85e4b52125cf50fc426",
          "sha1": "0690fe91fdcdf6753b6fac4a6945b35d453cbda0",
          "md5": "b3c58f902a7485c46a50a52c072117c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-1.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-1.jar",
          "size": 6253,
          "sha512": "95dcdd66bae11a1b2da12eceb76db65e9e398376bcfe91c053f1cbede27d9828a37ccd3e562ab63a48acdb27c194674de81d103605380794d576b363beaabd06",
          "sha256": "257a8ba1a7059fc35e7b4e7c41ba0b3ce9c918a46e07d85e4b52125cf50fc426",
          "sha1": "0690fe91fdcdf6753b6fac4a6945b35d453cbda0",
          "md5": "b3c58f902a7485c46a50a52c072117c2"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "9183ef56968b2e3508065f4c28a82c405f3a7041eecf783dc87ee41018eeb2155c6e4ca6dee5b183c00d465e22f021deb2713892734991227604d7906d273275",
          "sha256": "d8599c49b5ba84a019a0c755d5dc548362e8733072a5aff6153599f3961f965e",
          "sha1": "f0aaceb8f97a83e46449e44b837f8ad55bf21c39",
          "md5": "edbe9616a487d7aa48567e65ee74ae05"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-android-extensions-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-android-extensions",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-android-extensions-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-android-extensions-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "9183ef56968b2e3508065f4c28a82c405f3a7041eecf783dc87ee41018eeb2155c6e4ca6dee5b183c00d465e22f021deb2713892734991227604d7906d273275",
          "sha256": "d8599c49b5ba84a019a0c755d5dc548362e8733072a5aff6153599f3961f965e",
          "sha1": "f0aaceb8f97a83e46449e44b837f8ad55bf21c39",
          "md5": "edbe9616a487d7aa48567e65ee74ae05"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-android-extensions-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
