{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-auth-jwt/2.0.2-jitsi/ktor-server-auth-jwt-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-auth-jwt",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "com.auth0",
          "module": "jwks-rsa",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auth-jwt-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-auth-jwt-jvm-2.0.2-jitsi.jar",
          "size": 40815,
          "sha512": "17deca8fb06ec7aae0ebf6c0be466713d2db6f1f32b55971f54ee6fa6e9a7e17dae5a5a27c83001d68792c6f29d0e927edd65c00e0e65ff336de45bc04d6941d",
          "sha256": "eb914de0f23ca8ce939895ea0b857b0b9504649ab4137be681d4eab5eca5579a",
          "sha1": "8272b1ff31e507e87ad09afb4f7f842f0639e946",
          "md5": "1e108b5b541e8ef98265db805eb61699"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-auth",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "com.auth0",
          "module": "jwks-rsa",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-auth-jwt-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-auth-jwt-jvm-2.0.2-jitsi.jar",
          "size": 40815,
          "sha512": "17deca8fb06ec7aae0ebf6c0be466713d2db6f1f32b55971f54ee6fa6e9a7e17dae5a5a27c83001d68792c6f29d0e927edd65c00e0e65ff336de45bc04d6941d",
          "sha256": "eb914de0f23ca8ce939895ea0b857b0b9504649ab4137be681d4eab5eca5579a",
          "sha1": "8272b1ff31e507e87ad09afb4f7f842f0639e946",
          "md5": "1e108b5b541e8ef98265db805eb61699"
        }
      ]
    }
  ]
}
