{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-default-headers/2.0.2-jitsi/ktor-server-default-headers-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-default-headers",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-default-headers-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-default-headers-jvm-2.0.2-jitsi.jar",
          "size": 12876,
          "sha512": "74cc4469c3dce875d568da3f157189713f6f87abd8f9872afe46b56ecebf7d3ad3b918462d17946f4689e60cf2700fec075b1272fff0598269faac2aeb8ee7d7",
          "sha256": "2fa66cbdc465b757f4bb826aa7b9318bf7ddac09bbdfc6a24caea5089c40e7d3",
          "sha1": "08e01a8da78b72dc904ebcafe76def83f2217707",
          "md5": "086f6bd61707f09b6f61945c7f06d78f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-default-headers-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-default-headers-jvm-2.0.2-jitsi.jar",
          "size": 12876,
          "sha512": "74cc4469c3dce875d568da3f157189713f6f87abd8f9872afe46b56ecebf7d3ad3b918462d17946f4689e60cf2700fec075b1272fff0598269faac2aeb8ee7d7",
          "sha256": "2fa66cbdc465b757f4bb826aa7b9318bf7ddac09bbdfc6a24caea5089c40e7d3",
          "sha1": "08e01a8da78b72dc904ebcafe76def83f2217707",
          "md5": "086f6bd61707f09b6f61945c7f06d78f"
        }
      ]
    }
  ]
}
