{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client/2.0.2-jitsi/ktor-client-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-client",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-jvm-2.0.2-jitsi.jar",
          "size": 340,
          "sha512": "73bc88ec0b63ee888647d3f46de62ddc4dc46bd4b5de3a39c122966cd1f2370752a8490ca26defd2df2cc307cb09f2ba578dc139399657593cd77c0855487c7b",
          "sha256": "e67a5f918dd536321b814883516aabbbaf4139db725f47692d04341f5aff8011",
          "sha1": "d767e9c38daa4e26008b0f095110d22cdefaba1f",
          "md5": "5c65481958e75ac50e78fd2897c6a054"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-jvm-2.0.2-jitsi.jar",
          "url": "ktor-client-jvm-2.0.2-jitsi.jar",
          "size": 340,
          "sha512": "73bc88ec0b63ee888647d3f46de62ddc4dc46bd4b5de3a39c122966cd1f2370752a8490ca26defd2df2cc307cb09f2ba578dc139399657593cd77c0855487c7b",
          "sha256": "e67a5f918dd536321b814883516aabbbaf4139db725f47692d04341f5aff8011",
          "sha1": "d767e9c38daa4e26008b0f095110d22cdefaba1f",
          "md5": "5c65481958e75ac50e78fd2897c6a054"
        }
      ]
    }
  ]
}
