{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-content-negotiation/2.0.2-jitsi/ktor-server-content-negotiation-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-server-content-negotiation",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-content-negotiation-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-content-negotiation-jvm-2.0.2-jitsi.jar",
          "size": 32988,
          "sha512": "0e1ddf529d487c85e8d3b4a13816281255da5afa42d6269f0b2dd761e8fe154af7577ac49be0f0cbb7af0cd4bba89b5b03a5196a5e90f8611dd04859d27cff7e",
          "sha256": "7c46ab52072edabe49dea3526cff9526b16287009a9f7163227351cce724f380",
          "sha1": "e334399ceac22e618eb4c8352d1f2aca3b0b5c92",
          "md5": "993d5660eab1a9b2f9aaca4d6c9368e7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-content-negotiation-jvm-2.0.2-jitsi.jar",
          "url": "ktor-server-content-negotiation-jvm-2.0.2-jitsi.jar",
          "size": 32988,
          "sha512": "0e1ddf529d487c85e8d3b4a13816281255da5afa42d6269f0b2dd761e8fe154af7577ac49be0f0cbb7af0cd4bba89b5b03a5196a5e90f8611dd04859d27cff7e",
          "sha256": "7c46ab52072edabe49dea3526cff9526b16287009a9f7163227351cce724f380",
          "sha1": "e334399ceac22e618eb4c8352d1f2aca3b0b5c92",
          "md5": "993d5660eab1a9b2f9aaca4d6c9368e7"
        }
      ]
    }
  ]
}
