{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-minidns",
    "version": "4.4.8-jitsi-3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "g4w2765gmje7dijtp3gf35vrpy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-hla",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-util-cache",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-3.jar",
          "size": 7656,
          "sha512": "c0f5d06defc9cc2bb586fc590b68385b3bbfcb5de7f16fd80f0252a6649fd986b8afafc53d4b02a858765151c7cfe2dad18e1cbdae81efff1ef579a90eb76dbb",
          "sha256": "083025ff0a92b5f16fcee492d13a830eebd1fc308923e6e2bfd02b88c84ac764",
          "sha1": "77b7b7d26f5a7c79e82580e1cc842cb45ee7e509",
          "md5": "38cf3212418e3613c8a425b9b7e76571"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.minidns",
          "module": "minidns-hla",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        },
        {
          "group": "org.jxmpp",
          "module": "jxmpp-util-cache",
          "version": {
            "requires": "[1.0.0, 1.0.999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-3.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-3.jar",
          "size": 7656,
          "sha512": "c0f5d06defc9cc2bb586fc590b68385b3bbfcb5de7f16fd80f0252a6649fd986b8afafc53d4b02a858765151c7cfe2dad18e1cbdae81efff1ef579a90eb76dbb",
          "sha256": "083025ff0a92b5f16fcee492d13a830eebd1fc308923e6e2bfd02b88c84ac764",
          "sha1": "77b7b7d26f5a7c79e82580e1cc842cb45ee7e509",
          "md5": "38cf3212418e3613c8a425b9b7e76571"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "23408e865776b88a4e5609001757f76e570cde53089f014990506236d5055af92ccbe8030e6c88e9d50299ae3bd0ebce4c5c1a6c483ed537947048b90f0b1110",
          "sha256": "cb8526a2cbec28498c40573ed4f2919f7590024d36a86b888116ac49d9748fd8",
          "sha1": "51eab69bebd2b2bcee98381175ba73330e1afb92",
          "md5": "dcb69cc0b45f9fc9ef7cf3494775d758"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-minidns-4.4.8-jitsi-3-test-fixtures.jar",
          "url": "smack-resolver-minidns-4.4.8-jitsi-3-test-fixtures.jar",
          "size": 261,
          "sha512": "23408e865776b88a4e5609001757f76e570cde53089f014990506236d5055af92ccbe8030e6c88e9d50299ae3bd0ebce4c5c1a6c483ed537947048b90f0b1110",
          "sha256": "cb8526a2cbec28498c40573ed4f2919f7590024d36a86b888116ac49d9748fd8",
          "sha1": "51eab69bebd2b2bcee98381175ba73330e1afb92",
          "md5": "dcb69cc0b45f9fc9ef7cf3494775d758"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-minidns-test-fixtures",
          "version": "4.4.8-jitsi-3"
        }
      ]
    }
  ]
}
