{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-resolver-dnsjava",
    "version": "4.4.8-jitsi-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "e7plrzovkne35avlozsp3dpmte"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "[3.0.0,3.0.9999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-1.jar",
          "size": 3407,
          "sha512": "48f643036c55fa43a36ebaef00878bab5c125ab9f836736d798ff26556dd22c1cd4dc63863aaa60e8d8f8da21e20682e5462b9565ef82c89f900c18590c07b86",
          "sha256": "1819349f51e324a8db01a22b2148509325445d62ab249eab2c9e67787c8f54f2",
          "sha1": "d3b1acd52f31a2560797904a482f720567a7134c",
          "md5": "c9339068eea1b3312a9535652412bca1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-core",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "dnsjava",
          "module": "dnsjava",
          "version": {
            "requires": "[3.0.0,3.0.9999]"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-1.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-1.jar",
          "size": 3407,
          "sha512": "48f643036c55fa43a36ebaef00878bab5c125ab9f836736d798ff26556dd22c1cd4dc63863aaa60e8d8f8da21e20682e5462b9565ef82c89f900c18590c07b86",
          "sha256": "1819349f51e324a8db01a22b2148509325445d62ab249eab2c9e67787c8f54f2",
          "sha1": "d3b1acd52f31a2560797904a482f720567a7134c",
          "md5": "c9339068eea1b3312a9535652412bca1"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-dnsjava",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-dnsjava-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-dnsjava",
          "version": {
            "requires": "4.4.8-jitsi-1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-resolver-dnsjava-4.4.8-jitsi-1-test-fixtures.jar",
          "url": "smack-resolver-dnsjava-4.4.8-jitsi-1-test-fixtures.jar",
          "size": 261,
          "sha512": "5935c09e0bfe4d72704ee9d9ba40b6239c52db87ead7014c3c67b98cd7d619b98e68c22b64131af8c37c5ed5e99ffaa7524856be5723fbd904ee88ee203eb671",
          "sha256": "06ce9fefee070bea7d867361ce29da1c29809bd2a4da793de7e9a3102b347f4c",
          "sha1": "b39690839408f285a294cc7deb1e1c569d74e146",
          "md5": "791d291505f4bc92f808c2438a10f22a"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-resolver-dnsjava-test-fixtures",
          "version": "4.4.8-jitsi-1"
        }
      ]
    }
  ]
}
