{
  "formatVersion": "1.1",
  "component": {
    "group": "org.igniterealtime.smack",
    "module": "smack-java8-full",
    "version": "4.4.8-jitsi-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uuvftdk5hzaffihqimktnt4x7e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-2.jar",
          "url": "smack-java8-full-4.4.8-jitsi-2.jar",
          "size": 2646,
          "sha512": "f2c1806cb1e7c9c0973be1aee1e2d95ec57f346df24b0f3ee22a1d70f6b73f30fce04f4e2b6528e665add0cf00380495db06680e42b38d0273e65431d82dec54",
          "sha256": "3ac5a1581e4ab807dd6cdcd3c442070584f5c353019d827ba88174cdd4175087",
          "sha1": "834ad03b3eef1b36c4cbd80f55e0e1198b65460f",
          "md5": "af53a642a246d2d03211e6c2bf255994"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-bosh",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-debug",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-experimental",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-extensions",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-legacy",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-omemo",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-openpgp",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-resolver-minidns-dox",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-tcp",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-2.jar",
          "url": "smack-java8-full-4.4.8-jitsi-2.jar",
          "size": 2646,
          "sha512": "f2c1806cb1e7c9c0973be1aee1e2d95ec57f346df24b0f3ee22a1d70f6b73f30fce04f4e2b6528e665add0cf00380495db06680e42b38d0273e65431d82dec54",
          "sha256": "3ac5a1581e4ab807dd6cdcd3c442070584f5c353019d827ba88174cdd4175087",
          "sha1": "834ad03b3eef1b36c4cbd80f55e0e1198b65460f",
          "md5": "af53a642a246d2d03211e6c2bf255994"
        }
      ]
    },
    {
      "name": "testFixturesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-2-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-2-test-fixtures.jar",
          "size": 261,
          "sha512": "4ba9ae07d00ec718d15d768f0dafb7b3b0d4016315f20e5ecd8b279d35848626c6691013f1588eea2305b8ce38a228a5cf4f2c74e348505502922f1cc0cad425",
          "sha256": "d1efc26862963f3cd755d4eae1343b5da9562a8d1a8af64dad73b78997888204",
          "sha1": "64bd5ca2dde5a28c7aa18a71ce2c6e666efcd07f",
          "md5": "6736484687555fa4ad01bb333cccc3bd"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-2"
        }
      ]
    },
    {
      "name": "testFixturesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.igniterealtime.smack",
          "module": "smack-java8-full",
          "version": {
            "requires": "4.4.8-jitsi-2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.7.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "smack-java8-full-4.4.8-jitsi-2-test-fixtures.jar",
          "url": "smack-java8-full-4.4.8-jitsi-2-test-fixtures.jar",
          "size": 261,
          "sha512": "4ba9ae07d00ec718d15d768f0dafb7b3b0d4016315f20e5ecd8b279d35848626c6691013f1588eea2305b8ce38a228a5cf4f2c74e348505502922f1cc0cad425",
          "sha256": "d1efc26862963f3cd755d4eae1343b5da9562a8d1a8af64dad73b78997888204",
          "sha1": "64bd5ca2dde5a28c7aa18a71ce2c6e666efcd07f",
          "md5": "6736484687555fa4ad01bb333cccc3bd"
        }
      ],
      "capabilities": [
        {
          "group": "org.igniterealtime.smack",
          "name": "smack-java8-full-test-fixtures",
          "version": "4.4.8-jitsi-2"
        }
      ]
    }
  ]
}
