{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-json/2.0.2-jitsi/ktor-serialization-kotlinx-json-2.0.2-jitsi.module",
    "group": "io.ktor",
    "module": "ktor-serialization-kotlinx-json",
    "version": "2.0.2-jitsi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-jvm-2.0.2-jitsi.jar",
          "url": "ktor-serialization-kotlinx-json-jvm-2.0.2-jitsi.jar",
          "size": 3644,
          "sha512": "bb34f606ed098cdd89349c34b01f6a0c29b7a448798dad69dcbc4ee0cdbc9670ab29a1a6b5e9269f911cf6a7cf238512159abc1ff67bf245d533421d09020196",
          "sha256": "a4d7b9a22326ef985ea3f920368b3ee0144cc755963b314cef71b8816423788f",
          "sha1": "101fae6caf3cb1bbf50c24f0760935f16ee086bb",
          "md5": "e23e0ff8d3b6daa7f30341b7c9a165c2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.0.2-jitsi"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-jvm-2.0.2-jitsi.jar",
          "url": "ktor-serialization-kotlinx-json-jvm-2.0.2-jitsi.jar",
          "size": 3644,
          "sha512": "bb34f606ed098cdd89349c34b01f6a0c29b7a448798dad69dcbc4ee0cdbc9670ab29a1a6b5e9269f911cf6a7cf238512159abc1ff67bf245d533421d09020196",
          "sha256": "a4d7b9a22326ef985ea3f920368b3ee0144cc755963b314cef71b8816423788f",
          "sha1": "101fae6caf3cb1bbf50c24f0760935f16ee086bb",
          "md5": "e23e0ff8d3b6daa7f30341b7c9a165c2"
        }
      ]
    }
  ]
}
